macro_line|#ifndef _ASM_IA64_OFFSETS_H
DECL|macro|_ASM_IA64_OFFSETS_H
mdefine_line|#define _ASM_IA64_OFFSETS_H
multiline_comment|/*&n; * DO NOT MODIFY&n; *&n; * This file was generated by arch/ia64/tools/print_offsets.&n; *&n; */
DECL|macro|PF_PTRACED_BIT
mdefine_line|#define PF_PTRACED_BIT&t;&t;&t;4
DECL|macro|IA64_TASK_SIZE
mdefine_line|#define IA64_TASK_SIZE&t;&t;&t;2816&t;/* 0xb00 */
DECL|macro|IA64_PT_REGS_SIZE
mdefine_line|#define IA64_PT_REGS_SIZE&t;&t;400&t;/* 0x190 */
DECL|macro|IA64_SWITCH_STACK_SIZE
mdefine_line|#define IA64_SWITCH_STACK_SIZE&t;&t;560&t;/* 0x230 */
DECL|macro|IA64_SIGINFO_SIZE
mdefine_line|#define IA64_SIGINFO_SIZE&t;&t;136&t;/* 0x88 */
DECL|macro|IA64_TASK_FLAGS_OFFSET
mdefine_line|#define IA64_TASK_FLAGS_OFFSET&t;&t;8&t;/* 0x8 */
DECL|macro|IA64_TASK_SIGPENDING_OFFSET
mdefine_line|#define IA64_TASK_SIGPENDING_OFFSET&t;16&t;/* 0x10 */
DECL|macro|IA64_TASK_NEED_RESCHED_OFFSET
mdefine_line|#define IA64_TASK_NEED_RESCHED_OFFSET&t;40&t;/* 0x28 */
DECL|macro|IA64_TASK_PROCESSOR_OFFSET
mdefine_line|#define IA64_TASK_PROCESSOR_OFFSET&t;108&t;/* 0x6c */
DECL|macro|IA64_TASK_THREAD_OFFSET
mdefine_line|#define IA64_TASK_THREAD_OFFSET&t;&t;928&t;/* 0x3a0 */
DECL|macro|IA64_TASK_THREAD_KSP_OFFSET
mdefine_line|#define IA64_TASK_THREAD_KSP_OFFSET&t;928&t;/* 0x3a0 */
DECL|macro|IA64_TASK_THREAD_SIGMASK_OFFSET
mdefine_line|#define IA64_TASK_THREAD_SIGMASK_OFFSET&t;2656&t;/* 0xa60 */
DECL|macro|IA64_TASK_PID_OFFSET
mdefine_line|#define IA64_TASK_PID_OFFSET&t;&t;188&t;/* 0xbc */
DECL|macro|IA64_TASK_MM_OFFSET
mdefine_line|#define IA64_TASK_MM_OFFSET&t;&t;88&t;/* 0x58 */
DECL|macro|IA64_PT_REGS_CR_IPSR_OFFSET
mdefine_line|#define IA64_PT_REGS_CR_IPSR_OFFSET&t;0&t;/* 0x0 */
DECL|macro|IA64_PT_REGS_R12_OFFSET
mdefine_line|#define IA64_PT_REGS_R12_OFFSET&t;&t;112&t;/* 0x70 */
DECL|macro|IA64_PT_REGS_R8_OFFSET
mdefine_line|#define IA64_PT_REGS_R8_OFFSET&t;&t;144&t;/* 0x90 */
DECL|macro|IA64_PT_REGS_R16_OFFSET
mdefine_line|#define IA64_PT_REGS_R16_OFFSET&t;&t;176&t;/* 0xb0 */
DECL|macro|IA64_SWITCH_STACK_B0_OFFSET
mdefine_line|#define IA64_SWITCH_STACK_B0_OFFSET&t;464&t;/* 0x1d0 */
DECL|macro|IA64_SWITCH_STACK_CALLER_UNAT_OFFSET
mdefine_line|#define IA64_SWITCH_STACK_CALLER_UNAT_OFFSET 0&t;/* 0x0 */
DECL|macro|IA64_SIGCONTEXT_AR_BSP_OFFSET
mdefine_line|#define IA64_SIGCONTEXT_AR_BSP_OFFSET&t;72&t;/* 0x48 */
DECL|macro|IA64_SIGCONTEXT_AR_RNAT_OFFSET
mdefine_line|#define IA64_SIGCONTEXT_AR_RNAT_OFFSET&t;80&t;/* 0x50 */
DECL|macro|IA64_SIGCONTEXT_FLAGS_OFFSET
mdefine_line|#define IA64_SIGCONTEXT_FLAGS_OFFSET&t;0&t;/* 0x0 */
DECL|macro|IA64_SIGCONTEXT_CFM_OFFSET
mdefine_line|#define IA64_SIGCONTEXT_CFM_OFFSET&t;48&t;/* 0x30 */
DECL|macro|IA64_SIGCONTEXT_FR6_OFFSET
mdefine_line|#define IA64_SIGCONTEXT_FR6_OFFSET&t;560&t;/* 0x230 */
DECL|macro|IA64_CLONE_VFORK
mdefine_line|#define IA64_CLONE_VFORK&t;&t;&t;16384&t;/* 0x4000 */
DECL|macro|IA64_CLONE_VM
mdefine_line|#define IA64_CLONE_VM&t;&t;&t;256&t;/* 0x100 */
macro_line|#endif /* _ASM_IA64_OFFSETS_H */
eof
