multiline_comment|/*&n; * WARNING! This file is automatically generated - DO NOT EDIT!&n; */
DECL|macro|STATE
mdefine_line|#define STATE 0
DECL|macro|COUNTER
mdefine_line|#define COUNTER 4
DECL|macro|BLOCKED
mdefine_line|#define BLOCKED 16
DECL|macro|SIGNAL
mdefine_line|#define SIGNAL 12
DECL|macro|KERNEL_STACK_PAGE
mdefine_line|#define KERNEL_STACK_PAGE 88
DECL|macro|TSS
mdefine_line|#define TSS 504
DECL|macro|KSP
mdefine_line|#define KSP 0
DECL|macro|MMU_SEG0
mdefine_line|#define MMU_SEG0 8
DECL|macro|MMU_SEG1
mdefine_line|#define MMU_SEG1 12
DECL|macro|MMU_SEG2
mdefine_line|#define MMU_SEG2 16
DECL|macro|MMU_SEG3
mdefine_line|#define MMU_SEG3 20
DECL|macro|MMU_SEG4
mdefine_line|#define MMU_SEG4 24
DECL|macro|MMU_SEG5
mdefine_line|#define MMU_SEG5 28
DECL|macro|MMU_SEG6
mdefine_line|#define MMU_SEG6 32
DECL|macro|MMU_SEG7
mdefine_line|#define MMU_SEG7 36
DECL|macro|MMU_SEG8
mdefine_line|#define MMU_SEG8 40
DECL|macro|MMU_SEG9
mdefine_line|#define MMU_SEG9 44
DECL|macro|MMU_SEG10
mdefine_line|#define MMU_SEG10 48
DECL|macro|MMU_SEG11
mdefine_line|#define MMU_SEG11 52
DECL|macro|MMU_SEG12
mdefine_line|#define MMU_SEG12 56
DECL|macro|MMU_SEG13
mdefine_line|#define MMU_SEG13 60
DECL|macro|MMU_SEG14
mdefine_line|#define MMU_SEG14 64
DECL|macro|MMU_SEG15
mdefine_line|#define MMU_SEG15 68
DECL|macro|TSS_FPR0
mdefine_line|#define TSS_FPR0 72
DECL|macro|TSS_FPR1
mdefine_line|#define TSS_FPR1 80
DECL|macro|TSS_FPR2
mdefine_line|#define TSS_FPR2 88
DECL|macro|TSS_FPR3
mdefine_line|#define TSS_FPR3 96
DECL|macro|TSS_FPR4
mdefine_line|#define TSS_FPR4 104
DECL|macro|TSS_FPR5
mdefine_line|#define TSS_FPR5 112
DECL|macro|TSS_FPR6
mdefine_line|#define TSS_FPR6 120
DECL|macro|TSS_FPR7
mdefine_line|#define TSS_FPR7 128
DECL|macro|TSS_FPR8
mdefine_line|#define TSS_FPR8 136
DECL|macro|TSS_FPR9
mdefine_line|#define TSS_FPR9 144
DECL|macro|TSS_FPR10
mdefine_line|#define TSS_FPR10 152
DECL|macro|TSS_FPR11
mdefine_line|#define TSS_FPR11 160
DECL|macro|TSS_FPR12
mdefine_line|#define TSS_FPR12 168
DECL|macro|TSS_FPR13
mdefine_line|#define TSS_FPR13 176
DECL|macro|TSS_FPR14
mdefine_line|#define TSS_FPR14 184
DECL|macro|TSS_FPR15
mdefine_line|#define TSS_FPR15 192
DECL|macro|TSS_FPR16
mdefine_line|#define TSS_FPR16 200
DECL|macro|TSS_FPR17
mdefine_line|#define TSS_FPR17 208
DECL|macro|TSS_FPR18
mdefine_line|#define TSS_FPR18 216
DECL|macro|TSS_FPR19
mdefine_line|#define TSS_FPR19 224
DECL|macro|TSS_FPR20
mdefine_line|#define TSS_FPR20 232
DECL|macro|TSS_FPR21
mdefine_line|#define TSS_FPR21 240
DECL|macro|TSS_FPR22
mdefine_line|#define TSS_FPR22 248
DECL|macro|TSS_FPR23
mdefine_line|#define TSS_FPR23 256
DECL|macro|TSS_FPR24
mdefine_line|#define TSS_FPR24 264
DECL|macro|TSS_FPR25
mdefine_line|#define TSS_FPR25 272
DECL|macro|TSS_FPR26
mdefine_line|#define TSS_FPR26 280
DECL|macro|TSS_FPR27
mdefine_line|#define TSS_FPR27 288
DECL|macro|TSS_FPR28
mdefine_line|#define TSS_FPR28 296
DECL|macro|TSS_FPR29
mdefine_line|#define TSS_FPR29 304
DECL|macro|TSS_FPR30
mdefine_line|#define TSS_FPR30 312
DECL|macro|TSS_FPR31
mdefine_line|#define TSS_FPR31 320
DECL|macro|INT_FRAME_SIZE
mdefine_line|#define INT_FRAME_SIZE 384
DECL|macro|GPR0
mdefine_line|#define GPR0 56
DECL|macro|GPR1
mdefine_line|#define GPR1 60
DECL|macro|GPR2
mdefine_line|#define GPR2 64
DECL|macro|GPR3
mdefine_line|#define GPR3 68
DECL|macro|GPR4
mdefine_line|#define GPR4 72
DECL|macro|GPR5
mdefine_line|#define GPR5 76
DECL|macro|GPR6
mdefine_line|#define GPR6 80
DECL|macro|GPR7
mdefine_line|#define GPR7 84
DECL|macro|GPR8
mdefine_line|#define GPR8 88
DECL|macro|GPR9
mdefine_line|#define GPR9 92
DECL|macro|GPR10
mdefine_line|#define GPR10 96
DECL|macro|GPR11
mdefine_line|#define GPR11 100
DECL|macro|GPR12
mdefine_line|#define GPR12 104
DECL|macro|GPR13
mdefine_line|#define GPR13 108
DECL|macro|GPR14
mdefine_line|#define GPR14 112
DECL|macro|GPR15
mdefine_line|#define GPR15 116
DECL|macro|GPR16
mdefine_line|#define GPR16 120
DECL|macro|GPR17
mdefine_line|#define GPR17 124
DECL|macro|GPR18
mdefine_line|#define GPR18 128
DECL|macro|GPR19
mdefine_line|#define GPR19 132
DECL|macro|GPR20
mdefine_line|#define GPR20 136
DECL|macro|GPR21
mdefine_line|#define GPR21 140
DECL|macro|GPR22
mdefine_line|#define GPR22 144
DECL|macro|GPR23
mdefine_line|#define GPR23 148
DECL|macro|GPR24
mdefine_line|#define GPR24 152
DECL|macro|GPR25
mdefine_line|#define GPR25 156
DECL|macro|GPR26
mdefine_line|#define GPR26 160
DECL|macro|GPR27
mdefine_line|#define GPR27 164
DECL|macro|GPR28
mdefine_line|#define GPR28 168
DECL|macro|GPR29
mdefine_line|#define GPR29 172
DECL|macro|GPR30
mdefine_line|#define GPR30 176
DECL|macro|GPR31
mdefine_line|#define GPR31 180
DECL|macro|FPR0
mdefine_line|#define FPR0 256
DECL|macro|FPR1
mdefine_line|#define FPR1 264
DECL|macro|FPR2
mdefine_line|#define FPR2 272
DECL|macro|FPR3
mdefine_line|#define FPR3 280
DECL|macro|FPCSR
mdefine_line|#define FPCSR 288
DECL|macro|_NIP
mdefine_line|#define _NIP 184
DECL|macro|_MSR
mdefine_line|#define _MSR 188
DECL|macro|_CTR
mdefine_line|#define _CTR 192
DECL|macro|_LINK
mdefine_line|#define _LINK 196
DECL|macro|_CCR
mdefine_line|#define _CCR 200
DECL|macro|_XER
mdefine_line|#define _XER 208
DECL|macro|_DAR
mdefine_line|#define _DAR 212
DECL|macro|_DSISR
mdefine_line|#define _DSISR 216
DECL|macro|_HASH1
mdefine_line|#define _HASH1 220
DECL|macro|_HASH2
mdefine_line|#define _HASH2 224
DECL|macro|_IMISS
mdefine_line|#define _IMISS 228
DECL|macro|_DMISS
mdefine_line|#define _DMISS 232
DECL|macro|_ICMP
mdefine_line|#define _ICMP 236
DECL|macro|_DCMP
mdefine_line|#define _DCMP 240
DECL|macro|ORIG_GPR3
mdefine_line|#define ORIG_GPR3 244
DECL|macro|RESULT
mdefine_line|#define RESULT 248
DECL|macro|TRAP
mdefine_line|#define TRAP 296
DECL|macro|MARKER
mdefine_line|#define MARKER 300
eof
