multiline_comment|/*&n; *  linux/kernel/blk_drv/ramdisk.c&n; *&n; *  Written by Theodore Ts&squot;o, 12/2/91&n; *&n; * Modifications by Fred N. van Kempen to allow for bootable root&n; * disks (which are used in LINUX/Pro).  Also some cleanups.  03/03/93&n; */
macro_line|#include &lt;linux/sched.h&gt;
macro_line|#include &lt;linux/minix_fs.h&gt;
macro_line|#include &lt;linux/ext2_fs.h&gt;
macro_line|#include &lt;linux/fs.h&gt;
macro_line|#include &lt;linux/kernel.h&gt;
macro_line|#include &lt;linux/string.h&gt;
macro_line|#include &lt;linux/mm.h&gt;
macro_line|#include &lt;asm/system.h&gt;
macro_line|#include &lt;asm/segment.h&gt;
DECL|macro|MAJOR_NR
mdefine_line|#define MAJOR_NR  MEM_MAJOR
macro_line|#include &lt;linux/blk.h&gt;
DECL|macro|RAMDISK_MINOR
mdefine_line|#define RAMDISK_MINOR&t;1
DECL|variable|rd_start
r_char
op_star
id|rd_start
suffix:semicolon
DECL|variable|rd_length
r_int
id|rd_length
op_assign
l_int|0
suffix:semicolon
DECL|variable|rd_blocksizes
r_static
r_int
id|rd_blocksizes
(braket
l_int|2
)braket
op_assign
(brace
l_int|0
comma
l_int|0
)brace
suffix:semicolon
DECL|function|rd_request
r_static
r_void
id|rd_request
c_func
(paren
r_void
)paren
(brace
r_int
id|len
suffix:semicolon
r_char
op_star
id|addr
suffix:semicolon
id|repeat
suffix:colon
id|INIT_REQUEST
suffix:semicolon
id|addr
op_assign
id|rd_start
op_plus
(paren
id|CURRENT-&gt;sector
op_lshift
l_int|9
)paren
suffix:semicolon
id|len
op_assign
id|CURRENT-&gt;current_nr_sectors
op_lshift
l_int|9
suffix:semicolon
r_if
c_cond
(paren
id|CURRENT
op_member_access_from_pointer
id|cmd
op_eq
id|WRITE
)paren
(brace
(paren
r_void
)paren
id|memcpy
c_func
(paren
id|addr
comma
id|CURRENT-&gt;buffer
comma
id|len
)paren
suffix:semicolon
)brace
r_else
r_if
c_cond
(paren
id|CURRENT-&gt;cmd
op_eq
id|READ
)paren
(brace
(paren
r_void
)paren
id|memcpy
c_func
(paren
id|CURRENT-&gt;buffer
comma
id|addr
comma
id|len
)paren
suffix:semicolon
)brace
r_else
id|panic
c_func
(paren
l_string|&quot;RAMDISK: unknown RAM disk command !&bslash;n&quot;
)paren
suffix:semicolon
id|end_request
c_func
(paren
l_int|1
)paren
suffix:semicolon
r_goto
id|repeat
suffix:semicolon
)brace
DECL|variable|rd_fops
r_static
r_struct
id|file_operations
id|rd_fops
op_assign
(brace
l_int|NULL
comma
multiline_comment|/* lseek - default */
id|block_read
comma
multiline_comment|/* read - general block-dev read */
id|block_write
comma
multiline_comment|/* write - general block-dev write */
l_int|NULL
comma
multiline_comment|/* readdir - bad */
l_int|NULL
comma
multiline_comment|/* select */
l_int|NULL
comma
multiline_comment|/* ioctl */
l_int|NULL
comma
multiline_comment|/* mmap */
l_int|NULL
comma
multiline_comment|/* no special open code */
l_int|NULL
comma
multiline_comment|/* no special release code */
id|block_fsync
multiline_comment|/* fsync */
)brace
suffix:semicolon
r_void
DECL|function|rd_preloaded_init
id|rd_preloaded_init
c_func
(paren
r_char
op_star
id|start
comma
r_int
id|length
)paren
(brace
r_int
id|i
suffix:semicolon
r_if
c_cond
(paren
id|register_blkdev
c_func
(paren
id|MEM_MAJOR
comma
l_string|&quot;rd&quot;
comma
op_amp
id|rd_fops
)paren
)paren
(brace
id|printk
c_func
(paren
l_string|&quot;RAMDISK: Unable to get major %d.&bslash;n&quot;
comma
id|MEM_MAJOR
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
id|blk_dev
(braket
id|MEM_MAJOR
)braket
dot
id|request_fn
op_assign
id|DEVICE_REQUEST
suffix:semicolon
id|rd_start
op_assign
id|start
suffix:semicolon
id|rd_length
op_assign
id|length
suffix:semicolon
r_for
c_loop
(paren
id|i
op_assign
l_int|0
suffix:semicolon
id|i
OL
l_int|2
suffix:semicolon
id|i
op_increment
)paren
(brace
id|rd_blocksizes
(braket
id|i
)braket
op_assign
l_int|1024
suffix:semicolon
)brace
id|blksize_size
(braket
id|MAJOR_NR
)braket
op_assign
id|rd_blocksizes
suffix:semicolon
multiline_comment|/* We loaded the file system image.  Prepare for mounting it. */
id|ROOT_DEV
op_assign
id|to_kdev_t
c_func
(paren
(paren
id|MEM_MAJOR
op_lshift
l_int|8
)paren
op_or
id|RAMDISK_MINOR
)paren
suffix:semicolon
)brace
eof
