multiline_comment|/*&n; *  Zorro board IDs&n; *&n; *  Please keep sorted.&n; */
DECL|macro|ZORRO_MANUF_PACIFIC_PERIPHERALS
mdefine_line|#define ZORRO_MANUF_PACIFIC_PERIPHERALS&t;&t;&t;&t;0x00D3
DECL|macro|ZORRO_PROD_PACIFIC_PERIPHERALS_SE_2000_A500
mdefine_line|#define  ZORRO_PROD_PACIFIC_PERIPHERALS_SE_2000_A500&t;&t;ZORRO_ID(PACIFIC_PERIPHERALS, 0x00, 0)
DECL|macro|ZORRO_PROD_PACIFIC_PERIPHERALS_SCSI
mdefine_line|#define  ZORRO_PROD_PACIFIC_PERIPHERALS_SCSI&t;&t;&t;ZORRO_ID(PACIFIC_PERIPHERALS, 0x0A, 0)
DECL|macro|ZORRO_MANUF_MACROSYSTEMS_USA_2
mdefine_line|#define ZORRO_MANUF_MACROSYSTEMS_USA_2&t;&t;&t;&t;0x0100
DECL|macro|ZORRO_PROD_MACROSYSTEMS_WARP_ENGINE
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_WARP_ENGINE&t;&t;&t;ZORRO_ID(MACROSYSTEMS_USA_2, 0x13, 0)
DECL|macro|ZORRO_MANUF_KUPKE_1
mdefine_line|#define ZORRO_MANUF_KUPKE_1&t;&t;&t;&t;&t;0x00DD
DECL|macro|ZORRO_PROD_KUPKE_GOLEM_RAM_BOX_2MB
mdefine_line|#define  ZORRO_PROD_KUPKE_GOLEM_RAM_BOX_2MB&t;&t;&t;ZORRO_ID(KUPKE_1, 0x00, 0)
DECL|macro|ZORRO_MANUF_MEMPHIS
mdefine_line|#define ZORRO_MANUF_MEMPHIS&t;&t;&t;&t;&t;0x0100
DECL|macro|ZORRO_PROD_MEMPHIS_STORMBRINGER
mdefine_line|#define  ZORRO_PROD_MEMPHIS_STORMBRINGER&t;&t;&t;ZORRO_ID(MEMPHIS, 0x00, 0)
DECL|macro|ZORRO_MANUF_3_STATE
mdefine_line|#define ZORRO_MANUF_3_STATE&t;&t;&t;&t;&t;0x0200
DECL|macro|ZORRO_PROD_3_STATE_MEGAMIX_2000
mdefine_line|#define  ZORRO_PROD_3_STATE_MEGAMIX_2000&t;&t;&t;ZORRO_ID(3_STATE, 0x02, 0)
DECL|macro|ZORRO_MANUF_COMMODORE_BRAUNSCHWEIG
mdefine_line|#define ZORRO_MANUF_COMMODORE_BRAUNSCHWEIG&t;&t;&t;0x0201
DECL|macro|ZORRO_PROD_CBM_A2088_A2286
mdefine_line|#define  ZORRO_PROD_CBM_A2088_A2286&t;&t;&t;&t;ZORRO_ID(COMMODORE_BRAUNSCHWEIG, 0x01, 0)
DECL|macro|ZORRO_PROD_CBM_A2286
mdefine_line|#define  ZORRO_PROD_CBM_A2286&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_BRAUNSCHWEIG, 0x02, 0)
DECL|macro|ZORRO_PROD_CBM_A4091_1
mdefine_line|#define  ZORRO_PROD_CBM_A4091_1&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_BRAUNSCHWEIG, 0x54, 0)
DECL|macro|ZORRO_PROD_CBM_A2386SX_1
mdefine_line|#define  ZORRO_PROD_CBM_A2386SX_1&t;&t;&t;&t;ZORRO_ID(COMMODORE_BRAUNSCHWEIG, 0x67, 0)
DECL|macro|ZORRO_MANUF_COMMODORE_WEST_CHESTER_1
mdefine_line|#define ZORRO_MANUF_COMMODORE_WEST_CHESTER_1&t;&t;&t;0x0202
DECL|macro|ZORRO_PROD_CBM_A2090A
mdefine_line|#define  ZORRO_PROD_CBM_A2090A&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x01, 0)
DECL|macro|ZORRO_PROD_CBM_A590_A2091_1
mdefine_line|#define  ZORRO_PROD_CBM_A590_A2091_1&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x02, 0)
DECL|macro|ZORRO_PROD_CBM_A590_A2091_2
mdefine_line|#define  ZORRO_PROD_CBM_A590_A2091_2&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x03, 0)
DECL|macro|ZORRO_PROD_CBM_A2090B
mdefine_line|#define  ZORRO_PROD_CBM_A2090B&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x04, 0)
DECL|macro|ZORRO_PROD_CBM_A2060
mdefine_line|#define  ZORRO_PROD_CBM_A2060&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x09, 0)
DECL|macro|ZORRO_PROD_CBM_A590_A2052_A2058_A2091
mdefine_line|#define  ZORRO_PROD_CBM_A590_A2052_A2058_A2091&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x0A, 0)
DECL|macro|ZORRO_PROD_CBM_A560_RAM
mdefine_line|#define  ZORRO_PROD_CBM_A560_RAM&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x20, 0)
DECL|macro|ZORRO_PROD_CBM_A2232_PROTOTYPE
mdefine_line|#define  ZORRO_PROD_CBM_A2232_PROTOTYPE&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x45, 0)
DECL|macro|ZORRO_PROD_CBM_A2232
mdefine_line|#define  ZORRO_PROD_CBM_A2232&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x46, 0)
DECL|macro|ZORRO_PROD_CBM_A2620
mdefine_line|#define  ZORRO_PROD_CBM_A2620&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x50, 0)
DECL|macro|ZORRO_PROD_CBM_A2630
mdefine_line|#define  ZORRO_PROD_CBM_A2630&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x51, 0)
DECL|macro|ZORRO_PROD_CBM_A4091_2
mdefine_line|#define  ZORRO_PROD_CBM_A4091_2&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x54, 0)
DECL|macro|ZORRO_PROD_CBM_A2065_1
mdefine_line|#define  ZORRO_PROD_CBM_A2065_1&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x5A, 0)
DECL|macro|ZORRO_PROD_CBM_ROMULATOR
mdefine_line|#define  ZORRO_PROD_CBM_ROMULATOR&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x60, 0)
DECL|macro|ZORRO_PROD_CBM_A3000_TEST_FIXTURE
mdefine_line|#define  ZORRO_PROD_CBM_A3000_TEST_FIXTURE&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x61, 0)
DECL|macro|ZORRO_PROD_CBM_A2386SX_2
mdefine_line|#define  ZORRO_PROD_CBM_A2386SX_2&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x67, 0)
DECL|macro|ZORRO_PROD_CBM_A2065_2
mdefine_line|#define  ZORRO_PROD_CBM_A2065_2&t;&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_1, 0x70, 0)
DECL|macro|ZORRO_MANUF_COMMODORE_WEST_CHESTER_2
mdefine_line|#define ZORRO_MANUF_COMMODORE_WEST_CHESTER_2&t;&t;&t;0x0203
DECL|macro|ZORRO_PROD_CBM_A2090A_CM
mdefine_line|#define  ZORRO_PROD_CBM_A2090A_CM&t;&t;&t;&t;ZORRO_ID(COMMODORE_WEST_CHESTER_2, 0x03, 0)
DECL|macro|ZORRO_MANUF_PROGRESSIVE_PERIPHERALS_AND_SYSTEMS_2
mdefine_line|#define ZORRO_MANUF_PROGRESSIVE_PERIPHERALS_AND_SYSTEMS_2&t;0x02F4
DECL|macro|ZORRO_PROD_PPS_EXP8000
mdefine_line|#define  ZORRO_PROD_PPS_EXP8000&t;&t;&t;&t;&t;ZORRO_ID(PROGRESSIVE_PERIPHERALS_AND_SYSTEMS_2, 0x02, 0)
DECL|macro|ZORRO_MANUF_KOLFF_COMPUTER_SUPPLIES
mdefine_line|#define ZORRO_MANUF_KOLFF_COMPUTER_SUPPLIES&t;&t;&t;0x02FF
DECL|macro|ZORRO_PROD_KCS_POWER_PC_BOARD
mdefine_line|#define  ZORRO_PROD_KCS_POWER_PC_BOARD&t;&t;&t;&t;ZORRO_ID(KOLFF_COMPUTER_SUPPLIES, 0x00, 0)
DECL|macro|ZORRO_MANUF_CARDCO_1
mdefine_line|#define ZORRO_MANUF_CARDCO_1&t;&t;&t;&t;&t;0x03EC
DECL|macro|ZORRO_PROD_CARDCO_KRONOS_2000_1
mdefine_line|#define  ZORRO_PROD_CARDCO_KRONOS_2000_1&t;&t;&t;ZORRO_ID(CARDCO_1, 0x04, 0)
DECL|macro|ZORRO_PROD_CARDCO_A1000_1
mdefine_line|#define  ZORRO_PROD_CARDCO_A1000_1&t;&t;&t;&t;ZORRO_ID(CARDCO_1, 0x0C, 0)
DECL|macro|ZORRO_PROD_CARDCO_ESCORT
mdefine_line|#define  ZORRO_PROD_CARDCO_ESCORT&t;&t;&t;&t;ZORRO_ID(CARDCO_1, 0x0E, 0)
DECL|macro|ZORRO_PROD_CARDCO_A2410
mdefine_line|#define  ZORRO_PROD_CARDCO_A2410&t;&t;&t;&t;ZORRO_ID(CARDCO_1, 0xF5, 0)
DECL|macro|ZORRO_MANUF_A_SQUARED
mdefine_line|#define ZORRO_MANUF_A_SQUARED&t;&t;&t;&t;&t;0x03ED
DECL|macro|ZORRO_PROD_A_SQUARED_LIVE_2000
mdefine_line|#define  ZORRO_PROD_A_SQUARED_LIVE_2000&t;&t;&t;&t;ZORRO_ID(A_SQUARED, 0x01, 0)
DECL|macro|ZORRO_MANUF_COMSPEC_COMMUNICATIONS
mdefine_line|#define ZORRO_MANUF_COMSPEC_COMMUNICATIONS&t;&t;&t;0x03EE
DECL|macro|ZORRO_PROD_COMSPEC_COMMUNICATIONS_AX2000
mdefine_line|#define  ZORRO_PROD_COMSPEC_COMMUNICATIONS_AX2000&t;&t;ZORRO_ID(COMSPEC_COMMUNICATIONS, 0x01, 0)
DECL|macro|ZORRO_MANUF_ANAKIN_RESEARCH
mdefine_line|#define ZORRO_MANUF_ANAKIN_RESEARCH&t;&t;&t;&t;0x03F1
DECL|macro|ZORRO_PROD_ANAKIN_RESEARCH_EASYL
mdefine_line|#define  ZORRO_PROD_ANAKIN_RESEARCH_EASYL&t;&t;&t;ZORRO_ID(ANAKIN_RESEARCH, 0x01, 0)
DECL|macro|ZORRO_MANUF_MICROBOTICS
mdefine_line|#define ZORRO_MANUF_MICROBOTICS&t;&t;&t;&t;&t;0x03F2
DECL|macro|ZORRO_PROD_MICROBOTICS_STARBOARD_II
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_STARBOARD_II&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x00, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_STARDRIVE
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_STARDRIVE&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x02, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_8_UP_A
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_8_UP_A&t;&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x03, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_8_UP_Z
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_8_UP_Z&t;&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x04, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_DELTA_RAM
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_DELTA_RAM&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x20, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_8_STAR_RAM
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_8_STAR_RAM&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x40, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_8_STAR
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_8_STAR&t;&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x41, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_VXL_RAM_32
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_VXL_RAM_32&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x44, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_VXL_68030
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_VXL_68030&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x45, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_DELTA
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_DELTA&t;&t;&t;&t;ZORRO_ID(MICROBOTICS, 0x60, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_MBX_1200_1200Z_RAM
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_MBX_1200_1200Z_RAM&t;&t;ZORRO_ID(MICROBOTICS, 0x81, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_HARDFRAME_2000_1
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_HARDFRAME_2000_1&t;&t;ZORRO_ID(MICROBOTICS, 0x96, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_HARDFRAME_2000_2
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_HARDFRAME_2000_2&t;&t;ZORRO_ID(MICROBOTICS, 0x9E, 0)
DECL|macro|ZORRO_PROD_MICROBOTICS_MBX_1200_1200Z
mdefine_line|#define  ZORRO_PROD_MICROBOTICS_MBX_1200_1200Z&t;&t;&t;ZORRO_ID(MICROBOTICS, 0xC1, 0)
DECL|macro|ZORRO_MANUF_ACCESS_ASSOCIATES_ALEGRA
mdefine_line|#define ZORRO_MANUF_ACCESS_ASSOCIATES_ALEGRA&t;&t;&t;0x03F4
DECL|macro|ZORRO_MANUF_EXPANSION_TECHNOLOGIES
mdefine_line|#define ZORRO_MANUF_EXPANSION_TECHNOLOGIES&t;&t;&t;0x03F6
DECL|macro|ZORRO_MANUF_ASDG
mdefine_line|#define ZORRO_MANUF_ASDG&t;&t;&t;&t;&t;0x03FF
DECL|macro|ZORRO_PROD_ASDG_MEMORY_1
mdefine_line|#define  ZORRO_PROD_ASDG_MEMORY_1&t;&t;&t;&t;ZORRO_ID(ASDG, 0x01, 0)
DECL|macro|ZORRO_PROD_ASDG_MEMORY_2
mdefine_line|#define  ZORRO_PROD_ASDG_MEMORY_2&t;&t;&t;&t;ZORRO_ID(ASDG, 0x02, 0)
DECL|macro|ZORRO_PROD_ASDG_EB920_LAN_ROVER
mdefine_line|#define  ZORRO_PROD_ASDG_EB920_LAN_ROVER&t;&t;&t;ZORRO_ID(ASDG, 0xFE, 0)
DECL|macro|ZORRO_PROD_ASDG_GPIB_DUALIEEE488_TWIN_X
mdefine_line|#define  ZORRO_PROD_ASDG_GPIB_DUALIEEE488_TWIN_X&t;&t;ZORRO_ID(ASDG, 0xFF, 0)
DECL|macro|ZORRO_MANUF_IMTRONICS_1
mdefine_line|#define ZORRO_MANUF_IMTRONICS_1&t;&t;&t;&t;&t;0x0404
DECL|macro|ZORRO_PROD_IMTRONICS_HURRICANE_2800_1
mdefine_line|#define  ZORRO_PROD_IMTRONICS_HURRICANE_2800_1&t;&t;&t;ZORRO_ID(IMTRONICS_1, 0x39, 0)
DECL|macro|ZORRO_PROD_IMTRONICS_HURRICANE_2800_2
mdefine_line|#define  ZORRO_PROD_IMTRONICS_HURRICANE_2800_2&t;&t;&t;ZORRO_ID(IMTRONICS_1, 0x57, 0)
DECL|macro|ZORRO_MANUF_CBM_UNIVERSITY_OF_LOWELL
mdefine_line|#define ZORRO_MANUF_CBM_UNIVERSITY_OF_LOWELL&t;&t;&t;0x0406
DECL|macro|ZORRO_PROD_CBM_A2410
mdefine_line|#define  ZORRO_PROD_CBM_A2410&t;&t;&t;&t;&t;ZORRO_ID(CBM_UNIVERSITY_OF_LOWELL, 0x00, 0)
DECL|macro|ZORRO_MANUF_AMERISTAR
mdefine_line|#define ZORRO_MANUF_AMERISTAR&t;&t;&t;&t;&t;0x041D
DECL|macro|ZORRO_PROD_AMERISTAR_A2065
mdefine_line|#define  ZORRO_PROD_AMERISTAR_A2065&t;&t;&t;&t;ZORRO_ID(AMERISTAR, 0x01, 0)
DECL|macro|ZORRO_PROD_AMERISTAR_A560
mdefine_line|#define  ZORRO_PROD_AMERISTAR_A560&t;&t;&t;&t;ZORRO_ID(AMERISTAR, 0x09, 0)
DECL|macro|ZORRO_PROD_AMERISTAR_A4066
mdefine_line|#define  ZORRO_PROD_AMERISTAR_A4066&t;&t;&t;&t;ZORRO_ID(AMERISTAR, 0x0A, 0)
DECL|macro|ZORRO_MANUF_SUPRA
mdefine_line|#define ZORRO_MANUF_SUPRA&t;&t;&t;&t;&t;0x0420
DECL|macro|ZORRO_PROD_SUPRA_SUPRADRIVE_4x4
mdefine_line|#define  ZORRO_PROD_SUPRA_SUPRADRIVE_4x4&t;&t;&t;ZORRO_ID(SUPRA, 0x01, 0)
DECL|macro|ZORRO_PROD_SUPRA_1000_RAM
mdefine_line|#define  ZORRO_PROD_SUPRA_1000_RAM&t;&t;&t;&t;ZORRO_ID(SUPRA, 0x02, 0)
DECL|macro|ZORRO_PROD_SUPRA_2000_DMA
mdefine_line|#define  ZORRO_PROD_SUPRA_2000_DMA&t;&t;&t;&t;ZORRO_ID(SUPRA, 0x03, 0)
DECL|macro|ZORRO_PROD_SUPRA_500
mdefine_line|#define  ZORRO_PROD_SUPRA_500&t;&t;&t;&t;&t;ZORRO_ID(SUPRA, 0x05, 0)
DECL|macro|ZORRO_PROD_SUPRA_500_SCSI
mdefine_line|#define  ZORRO_PROD_SUPRA_500_SCSI&t;&t;&t;&t;ZORRO_ID(SUPRA, 0x08, 0)
DECL|macro|ZORRO_PROD_SUPRA_500XP_2000_RAM
mdefine_line|#define  ZORRO_PROD_SUPRA_500XP_2000_RAM&t;&t;&t;ZORRO_ID(SUPRA, 0x09, 0)
DECL|macro|ZORRO_PROD_SUPRA_500RX_2000_RAM
mdefine_line|#define  ZORRO_PROD_SUPRA_500RX_2000_RAM&t;&t;&t;ZORRO_ID(SUPRA, 0x0A, 0)
DECL|macro|ZORRO_PROD_SUPRA_2400ZI
mdefine_line|#define  ZORRO_PROD_SUPRA_2400ZI&t;&t;&t;&t;ZORRO_ID(SUPRA, 0x0B, 0)
DECL|macro|ZORRO_PROD_SUPRA_500XP_SUPRADRIVE_WORDSYNC
mdefine_line|#define  ZORRO_PROD_SUPRA_500XP_SUPRADRIVE_WORDSYNC&t;&t;ZORRO_ID(SUPRA, 0x0C, 0)
DECL|macro|ZORRO_PROD_SUPRA_SUPRADRIVE_WORDSYNC_II
mdefine_line|#define  ZORRO_PROD_SUPRA_SUPRADRIVE_WORDSYNC_II&t;&t;ZORRO_ID(SUPRA, 0x0D, 0)
DECL|macro|ZORRO_PROD_SUPRA_2400ZIPLUS
mdefine_line|#define  ZORRO_PROD_SUPRA_2400ZIPLUS&t;&t;&t;&t;ZORRO_ID(SUPRA, 0x10, 0)
DECL|macro|ZORRO_MANUF_COMPUTER_SYSTEMS_ASSOCIATES
mdefine_line|#define ZORRO_MANUF_COMPUTER_SYSTEMS_ASSOCIATES&t;&t;&t;0x0422
DECL|macro|ZORRO_PROD_CSA_MAGNUM
mdefine_line|#define  ZORRO_PROD_CSA_MAGNUM&t;&t;&t;&t;&t;ZORRO_ID(COMPUTER_SYSTEMS_ASSOCIATES, 0x11, 0)
DECL|macro|ZORRO_PROD_CSA_12_GAUGE
mdefine_line|#define  ZORRO_PROD_CSA_12_GAUGE&t;&t;&t;&t;ZORRO_ID(COMPUTER_SYSTEMS_ASSOCIATES, 0x15, 0)
DECL|macro|ZORRO_MANUF_MARC_MICHAEL_GROTH
mdefine_line|#define ZORRO_MANUF_MARC_MICHAEL_GROTH&t;&t;&t;&t;0x0439
DECL|macro|ZORRO_MANUF_M_TECH
mdefine_line|#define ZORRO_MANUF_M_TECH&t;&t;&t;&t;&t;0x0502
DECL|macro|ZORRO_PROD_MTEC_AT500_1
mdefine_line|#define  ZORRO_PROD_MTEC_AT500_1&t;&t;&t;&t;ZORRO_ID(M_TECH, 0x03, 0)
DECL|macro|ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_1
mdefine_line|#define ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_1&t;&t;&t;0x06E1
DECL|macro|ZORRO_PROD_GVP_IMPACT_SERIES_I
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_SERIES_I&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_1, 0x08, 0)
DECL|macro|ZORRO_MANUF_BYTEBOX
mdefine_line|#define ZORRO_MANUF_BYTEBOX&t;&t;&t;&t;&t;0x07DA
DECL|macro|ZORRO_PROD_BYTEBOX_A500
mdefine_line|#define  ZORRO_PROD_BYTEBOX_A500&t;&t;&t;&t;ZORRO_ID(BYTEBOX, 0x00, 0)
DECL|macro|ZORRO_MANUF_DKB_POWER_COMPUTING
mdefine_line|#define ZORRO_MANUF_DKB_POWER_COMPUTING&t;&t;&t;&t;0x07DC
DECL|macro|ZORRO_PROD_DKB_POWER_COMPUTING_SECUREKEY
mdefine_line|#define  ZORRO_PROD_DKB_POWER_COMPUTING_SECUREKEY&t;&t;ZORRO_ID(DKB_POWER_COMPUTING, 0x09, 0)
DECL|macro|ZORRO_PROD_DKB_POWER_COMPUTING_DKM_3128
mdefine_line|#define  ZORRO_PROD_DKB_POWER_COMPUTING_DKM_3128&t;&t;ZORRO_ID(DKB_POWER_COMPUTING, 0x0E, 0)
DECL|macro|ZORRO_PROD_DKB_POWER_COMPUTING_RAPID_FIRE
mdefine_line|#define  ZORRO_PROD_DKB_POWER_COMPUTING_RAPID_FIRE&t;&t;ZORRO_ID(DKB_POWER_COMPUTING, 0x0F, 0)
DECL|macro|ZORRO_PROD_DKB_POWER_COMPUTING_DKM_1202
mdefine_line|#define  ZORRO_PROD_DKB_POWER_COMPUTING_DKM_1202&t;&t;ZORRO_ID(DKB_POWER_COMPUTING, 0x10, 0)
DECL|macro|ZORRO_PROD_DKB_POWER_COMPUTING_COBRA_VIPER_II_68EC030
mdefine_line|#define  ZORRO_PROD_DKB_POWER_COMPUTING_COBRA_VIPER_II_68EC030&t;ZORRO_ID(DKB_POWER_COMPUTING, 0x12, 0)
DECL|macro|ZORRO_PROD_DKB_POWER_COMPUTING_WILDFIRE_060_1
mdefine_line|#define  ZORRO_PROD_DKB_POWER_COMPUTING_WILDFIRE_060_1&t;&t;ZORRO_ID(DKB_POWER_COMPUTING, 0x17, 0)
DECL|macro|ZORRO_PROD_DKB_POWER_COMPUTING_WILDFIRE_060_2
mdefine_line|#define  ZORRO_PROD_DKB_POWER_COMPUTING_WILDFIRE_060_2&t;&t;ZORRO_ID(DKB_POWER_COMPUTING, 0xFF, 0)
DECL|macro|ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_2
mdefine_line|#define ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_2&t;&t;&t;0x07E1
DECL|macro|ZORRO_PROD_GVP_IMPACT_SERIES_I_4K
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_SERIES_I_4K&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x01, 0)
DECL|macro|ZORRO_PROD_GVP_IMPACT_SERIES_I_16K_2
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_SERIES_I_16K_2&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x02, 0)
DECL|macro|ZORRO_PROD_GVP_IMPACT_SERIES_I_16K_3
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_SERIES_I_16K_3&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x03, 0)
DECL|macro|ZORRO_PROD_GVP_IMPACT_3001_IDE_1
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_3001_IDE_1&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x08, 0)
DECL|macro|ZORRO_PROD_GVP_IMPACT_3001_RAM
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_3001_RAM&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x09, 0)
DECL|macro|ZORRO_PROD_GVP_IMPACT_SERIES_II_RAM_1
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_SERIES_II_RAM_1&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0A, 0)
DECL|macro|ZORRO_PROD_GVP_EPC_BASE
mdefine_line|#define  ZORRO_PROD_GVP_EPC_BASE&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0)
DECL|macro|ZORRO_PROD_GVP_GFORCE_040_1
mdefine_line|#define  ZORRO_PROD_GVP_GFORCE_040_1&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0x20)
DECL|macro|ZORRO_PROD_GVP_GFORCE_040_SCSI_1
mdefine_line|#define  ZORRO_PROD_GVP_GFORCE_040_SCSI_1&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0x30)
DECL|macro|ZORRO_PROD_GVP_A1291
mdefine_line|#define  ZORRO_PROD_GVP_A1291&t;&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0x40)
DECL|macro|ZORRO_PROD_GVP_COMBO_030_R4
mdefine_line|#define  ZORRO_PROD_GVP_COMBO_030_R4&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0x60)
DECL|macro|ZORRO_PROD_GVP_COMBO_030_R4_SCSI
mdefine_line|#define  ZORRO_PROD_GVP_COMBO_030_R4_SCSI&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0x70)
DECL|macro|ZORRO_PROD_GVP_PHONEPAK
mdefine_line|#define  ZORRO_PROD_GVP_PHONEPAK&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0x78)
DECL|macro|ZORRO_PROD_GVP_IO_EXTENDER
mdefine_line|#define  ZORRO_PROD_GVP_IO_EXTENDER&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0x98)
DECL|macro|ZORRO_PROD_GVP_GFORCE_030
mdefine_line|#define  ZORRO_PROD_GVP_GFORCE_030&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0xa0)
DECL|macro|ZORRO_PROD_GVP_GFORCE_030_SCSI
mdefine_line|#define  ZORRO_PROD_GVP_GFORCE_030_SCSI&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0xb0)
DECL|macro|ZORRO_PROD_GVP_A530
mdefine_line|#define  ZORRO_PROD_GVP_A530&t;&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0xc0)
DECL|macro|ZORRO_PROD_GVP_A530_SCSI
mdefine_line|#define  ZORRO_PROD_GVP_A530_SCSI&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0xd0)
DECL|macro|ZORRO_PROD_GVP_COMBO_030_R3
mdefine_line|#define  ZORRO_PROD_GVP_COMBO_030_R3&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0xe0)
DECL|macro|ZORRO_PROD_GVP_COMBO_030_R3_SCSI
mdefine_line|#define  ZORRO_PROD_GVP_COMBO_030_R3_SCSI&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0xf0)
DECL|macro|ZORRO_PROD_GVP_SERIES_II
mdefine_line|#define  ZORRO_PROD_GVP_SERIES_II&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0B, 0xf8)
DECL|macro|ZORRO_PROD_GVP_IMPACT_3001_IDE_2
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_3001_IDE_2&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0D, 0)
multiline_comment|/*#define  ZORRO_PROD_GVP_A2000_030&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0D, 0)*/
multiline_comment|/*#define  ZORRO_PROD_GVP_GFORCE_040_SCSI_2&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x0D, 0)*/
DECL|macro|ZORRO_PROD_GVP_GFORCE_040_060
mdefine_line|#define  ZORRO_PROD_GVP_GFORCE_040_060&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x16, 0)
DECL|macro|ZORRO_PROD_GVP_IMPACT_VISION_24
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_VISION_24&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0x20, 0)
DECL|macro|ZORRO_PROD_GVP_GFORCE_040_2
mdefine_line|#define  ZORRO_PROD_GVP_GFORCE_040_2&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_2, 0xFF, 0)
DECL|macro|ZORRO_MANUF_CALIFORNIA_ACCESS_SYNERGY
mdefine_line|#define ZORRO_MANUF_CALIFORNIA_ACCESS_SYNERGY&t;&t;&t;0x07E5
DECL|macro|ZORRO_PROD_CALIFORNIA_ACCESS_SYNERGY_MALIBU
mdefine_line|#define  ZORRO_PROD_CALIFORNIA_ACCESS_SYNERGY_MALIBU&t;&t;ZORRO_ID(CALIFORNIA_ACCESS_SYNERGY, 0x01, 0)
DECL|macro|ZORRO_MANUF_XETEC
mdefine_line|#define ZORRO_MANUF_XETEC&t;&t;&t;&t;&t;0x07E6
DECL|macro|ZORRO_PROD_XETEC_FASTCARD
mdefine_line|#define  ZORRO_PROD_XETEC_FASTCARD&t;&t;&t;&t;ZORRO_ID(XETEC, 0x01, 0)
DECL|macro|ZORRO_PROD_XETEC_FASTCARD_RAM
mdefine_line|#define  ZORRO_PROD_XETEC_FASTCARD_RAM&t;&t;&t;&t;ZORRO_ID(XETEC, 0x02, 0)
DECL|macro|ZORRO_PROD_XETEC_FASTCARD_PLUS
mdefine_line|#define  ZORRO_PROD_XETEC_FASTCARD_PLUS&t;&t;&t;&t;ZORRO_ID(XETEC, 0x03, 0)
DECL|macro|ZORRO_MANUF_PROGRESSIVE_PERIPHERALS_AND_SYSTEMS
mdefine_line|#define ZORRO_MANUF_PROGRESSIVE_PERIPHERALS_AND_SYSTEMS&t;&t;0x07EA
DECL|macro|ZORRO_PROD_PPS_MERCURY
mdefine_line|#define  ZORRO_PROD_PPS_MERCURY&t;&t;&t;&t;&t;ZORRO_ID(PROGRESSIVE_PERIPHERALS_AND_SYSTEMS, 0x00, 0)
DECL|macro|ZORRO_PROD_PPS_A3000_68040
mdefine_line|#define  ZORRO_PROD_PPS_A3000_68040&t;&t;&t;&t;ZORRO_ID(PROGRESSIVE_PERIPHERALS_AND_SYSTEMS, 0x01, 0)
DECL|macro|ZORRO_PROD_PPS_A2000_68040
mdefine_line|#define  ZORRO_PROD_PPS_A2000_68040&t;&t;&t;&t;ZORRO_ID(PROGRESSIVE_PERIPHERALS_AND_SYSTEMS, 0x69, 0)
DECL|macro|ZORRO_PROD_PPS_ZEUS
mdefine_line|#define  ZORRO_PROD_PPS_ZEUS&t;&t;&t;&t;&t;ZORRO_ID(PROGRESSIVE_PERIPHERALS_AND_SYSTEMS, 0x96, 0)
DECL|macro|ZORRO_PROD_PPS_A500_68040
mdefine_line|#define  ZORRO_PROD_PPS_A500_68040&t;&t;&t;&t;ZORRO_ID(PROGRESSIVE_PERIPHERALS_AND_SYSTEMS, 0xBB, 0)
DECL|macro|ZORRO_MANUF_XEBEC
mdefine_line|#define ZORRO_MANUF_XEBEC&t;&t;&t;&t;&t;0x07EC
DECL|macro|ZORRO_MANUF_SPIRIT_TECHNOLOGY
mdefine_line|#define ZORRO_MANUF_SPIRIT_TECHNOLOGY&t;&t;&t;&t;0x07F2
DECL|macro|ZORRO_PROD_SPIRIT_TECHNOLOGY_INSIDER_IN1000
mdefine_line|#define  ZORRO_PROD_SPIRIT_TECHNOLOGY_INSIDER_IN1000&t;&t;ZORRO_ID(SPIRIT_TECHNOLOGY, 0x01, 0)
DECL|macro|ZORRO_PROD_SPIRIT_TECHNOLOGY_INSIDER_IN500
mdefine_line|#define  ZORRO_PROD_SPIRIT_TECHNOLOGY_INSIDER_IN500&t;&t;ZORRO_ID(SPIRIT_TECHNOLOGY, 0x02, 0)
DECL|macro|ZORRO_PROD_SPIRIT_TECHNOLOGY_SIN500
mdefine_line|#define  ZORRO_PROD_SPIRIT_TECHNOLOGY_SIN500&t;&t;&t;ZORRO_ID(SPIRIT_TECHNOLOGY, 0x03, 0)
DECL|macro|ZORRO_PROD_SPIRIT_TECHNOLOGY_HDA_506
mdefine_line|#define  ZORRO_PROD_SPIRIT_TECHNOLOGY_HDA_506&t;&t;&t;ZORRO_ID(SPIRIT_TECHNOLOGY, 0x04, 0)
DECL|macro|ZORRO_PROD_SPIRIT_TECHNOLOGY_AX_S
mdefine_line|#define  ZORRO_PROD_SPIRIT_TECHNOLOGY_AX_S&t;&t;&t;ZORRO_ID(SPIRIT_TECHNOLOGY, 0x05, 0)
DECL|macro|ZORRO_PROD_SPIRIT_TECHNOLOGY_OCTABYTE
mdefine_line|#define  ZORRO_PROD_SPIRIT_TECHNOLOGY_OCTABYTE&t;&t;&t;ZORRO_ID(SPIRIT_TECHNOLOGY, 0x06, 0)
DECL|macro|ZORRO_PROD_SPIRIT_TECHNOLOGY_INMATE
mdefine_line|#define  ZORRO_PROD_SPIRIT_TECHNOLOGY_INMATE&t;&t;&t;ZORRO_ID(SPIRIT_TECHNOLOGY, 0x08, 0)
DECL|macro|ZORRO_MANUF_SPIRIT_TECHNOLOGY_2
mdefine_line|#define ZORRO_MANUF_SPIRIT_TECHNOLOGY_2&t;&t;&t;&t;0x07F3
DECL|macro|ZORRO_MANUF_BSC_ALFADATA_1
mdefine_line|#define ZORRO_MANUF_BSC_ALFADATA_1&t;&t;&t;&t;0x07FE
DECL|macro|ZORRO_PROD_BSC_ALF_3_1
mdefine_line|#define  ZORRO_PROD_BSC_ALF_3_1&t;&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_1, 0x03, 0)
DECL|macro|ZORRO_MANUF_BSC_ALFADATA_2
mdefine_line|#define ZORRO_MANUF_BSC_ALFADATA_2&t;&t;&t;&t;0x0801
DECL|macro|ZORRO_PROD_BSC_ALF_2_1
mdefine_line|#define  ZORRO_PROD_BSC_ALF_2_1&t;&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_2, 0x01, 0)
DECL|macro|ZORRO_PROD_BSC_ALF_2_2
mdefine_line|#define  ZORRO_PROD_BSC_ALF_2_2&t;&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_2, 0x02, 0)
DECL|macro|ZORRO_PROD_BSC_ALF_3_2
mdefine_line|#define  ZORRO_PROD_BSC_ALF_3_2&t;&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_2, 0x03, 0)
DECL|macro|ZORRO_MANUF_CARDCO_2
mdefine_line|#define ZORRO_MANUF_CARDCO_2&t;&t;&t;&t;&t;0x0802
DECL|macro|ZORRO_PROD_CARDCO_KRONOS_2000_2
mdefine_line|#define  ZORRO_PROD_CARDCO_KRONOS_2000_2&t;&t;&t;ZORRO_ID(CARDCO_2, 0x04, 0)
DECL|macro|ZORRO_PROD_CARDCO_A1000_2
mdefine_line|#define  ZORRO_PROD_CARDCO_A1000_2&t;&t;&t;&t;ZORRO_ID(CARDCO_2, 0x0C, 0)
DECL|macro|ZORRO_MANUF_JOCHHEIM
mdefine_line|#define ZORRO_MANUF_JOCHHEIM&t;&t;&t;&t;&t;0x0804
DECL|macro|ZORRO_PROD_JOCHHEIM_RAM
mdefine_line|#define  ZORRO_PROD_JOCHHEIM_RAM&t;&t;&t;&t;ZORRO_ID(JOCHHEIM, 0x01, 0)
DECL|macro|ZORRO_MANUF_CHECKPOINT_TECHNOLOGIES
mdefine_line|#define ZORRO_MANUF_CHECKPOINT_TECHNOLOGIES&t;&t;&t;0x0807
DECL|macro|ZORRO_PROD_CHECKPOINT_TECHNOLOGIES_SERIAL_SOLUTION
mdefine_line|#define  ZORRO_PROD_CHECKPOINT_TECHNOLOGIES_SERIAL_SOLUTION&t;ZORRO_ID(CHECKPOINT_TECHNOLOGIES, 0x00, 0)
DECL|macro|ZORRO_MANUF_EDOTRONIK
mdefine_line|#define ZORRO_MANUF_EDOTRONIK&t;&t;&t;&t;&t;0x0810
DECL|macro|ZORRO_PROD_EDOTRONIK_IEEE_488
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_IEEE_488&t;&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x01, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_8032
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_8032&t;&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x02, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_MULTISERIAL
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_MULTISERIAL&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x03, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_VIDEODIGITIZER
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_VIDEODIGITIZER&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x04, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_PARALLEL_IO
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_PARALLEL_IO&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x05, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_PIC_PROTOYPING
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_PIC_PROTOYPING&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x06, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_ADC
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_ADC&t;&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x07, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_VME
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_VME&t;&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x08, 0)
DECL|macro|ZORRO_PROD_EDOTRONIK_DSP96000
mdefine_line|#define  ZORRO_PROD_EDOTRONIK_DSP96000&t;&t;&t;&t;ZORRO_ID(EDOTRONIK, 0x09, 0)
DECL|macro|ZORRO_MANUF_NES_INC
mdefine_line|#define ZORRO_MANUF_NES_INC&t;&t;&t;&t;&t;0x0813
DECL|macro|ZORRO_PROD_NES_INC_RAM
mdefine_line|#define  ZORRO_PROD_NES_INC_RAM&t;&t;&t;&t;&t;ZORRO_ID(NES_INC, 0x00, 0)
DECL|macro|ZORRO_MANUF_ICD
mdefine_line|#define ZORRO_MANUF_ICD&t;&t;&t;&t;&t;&t;0x0817
DECL|macro|ZORRO_PROD_ICD_ADVANTAGE_2000_SCSI
mdefine_line|#define  ZORRO_PROD_ICD_ADVANTAGE_2000_SCSI&t;&t;&t;ZORRO_ID(ICD, 0x01, 0)
DECL|macro|ZORRO_PROD_ICD_ADVANTAGE_IDE
mdefine_line|#define  ZORRO_PROD_ICD_ADVANTAGE_IDE&t;&t;&t;&t;ZORRO_ID(ICD, 0x03, 0)
DECL|macro|ZORRO_PROD_ICD_ADVANTAGE_2080_RAM
mdefine_line|#define  ZORRO_PROD_ICD_ADVANTAGE_2080_RAM&t;&t;&t;ZORRO_ID(ICD, 0x04, 0)
DECL|macro|ZORRO_MANUF_KUPKE_2
mdefine_line|#define ZORRO_MANUF_KUPKE_2&t;&t;&t;&t;&t;0x0819
DECL|macro|ZORRO_PROD_KUPKE_OMTI
mdefine_line|#define  ZORRO_PROD_KUPKE_OMTI&t;&t;&t;&t;&t;ZORRO_ID(KUPKE_2, 0x01, 0)
DECL|macro|ZORRO_PROD_KUPKE_SCSI_II
mdefine_line|#define  ZORRO_PROD_KUPKE_SCSI_II&t;&t;&t;&t;ZORRO_ID(KUPKE_2, 0x02, 0)
DECL|macro|ZORRO_PROD_KUPKE_GOLEM_BOX
mdefine_line|#define  ZORRO_PROD_KUPKE_GOLEM_BOX&t;&t;&t;&t;ZORRO_ID(KUPKE_2, 0x03, 0)
DECL|macro|ZORRO_PROD_KUPKE_030_882
mdefine_line|#define  ZORRO_PROD_KUPKE_030_882&t;&t;&t;&t;ZORRO_ID(KUPKE_2, 0x04, 0)
DECL|macro|ZORRO_PROD_KUPKE_SCSI_AT
mdefine_line|#define  ZORRO_PROD_KUPKE_SCSI_AT&t;&t;&t;&t;ZORRO_ID(KUPKE_2, 0x05, 0)
DECL|macro|ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_3
mdefine_line|#define ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_3&t;&t;&t;0x081D
DECL|macro|ZORRO_PROD_GVP_A2000_RAM8
mdefine_line|#define  ZORRO_PROD_GVP_A2000_RAM8&t;&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_3, 0x09, 0)
DECL|macro|ZORRO_PROD_GVP_IMPACT_SERIES_II_RAM_2
mdefine_line|#define  ZORRO_PROD_GVP_IMPACT_SERIES_II_RAM_2&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_3, 0x0A, 0)
DECL|macro|ZORRO_MANUF_INTERWORKS_NETWORK
mdefine_line|#define ZORRO_MANUF_INTERWORKS_NETWORK&t;&t;&t;&t;0x081E
DECL|macro|ZORRO_MANUF_HARDITAL_SYNTHESIS
mdefine_line|#define ZORRO_MANUF_HARDITAL_SYNTHESIS&t;&t;&t;&t;0x0820
DECL|macro|ZORRO_PROD_HARDITAL_SYNTHESIS_TQM_68030_68882
mdefine_line|#define  ZORRO_PROD_HARDITAL_SYNTHESIS_TQM_68030_68882&t;&t;ZORRO_ID(HARDITAL_SYNTHESIS, 0x14, 0)
DECL|macro|ZORRO_MANUF_APPLIED_ENGINEERING
mdefine_line|#define ZORRO_MANUF_APPLIED_ENGINEERING&t;&t;&t;&t;0x0828
DECL|macro|ZORRO_PROD_APPLIED_ENGINEERING_DL2000
mdefine_line|#define  ZORRO_PROD_APPLIED_ENGINEERING_DL2000&t;&t;&t;ZORRO_ID(APPLIED_ENGINEERING, 0x10, 0)
DECL|macro|ZORRO_PROD_APPLIED_ENGINEERING_RAM_WORKS
mdefine_line|#define  ZORRO_PROD_APPLIED_ENGINEERING_RAM_WORKS&t;&t;ZORRO_ID(APPLIED_ENGINEERING, 0xE0, 0)
DECL|macro|ZORRO_MANUF_BSC_ALFADATA_3
mdefine_line|#define ZORRO_MANUF_BSC_ALFADATA_3&t;&t;&t;&t;0x082C
DECL|macro|ZORRO_PROD_BSC_OKTAGON_2008
mdefine_line|#define  ZORRO_PROD_BSC_OKTAGON_2008&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x05, 0)
DECL|macro|ZORRO_PROD_BSC_TANDEM_AT_2008_508
mdefine_line|#define  ZORRO_PROD_BSC_TANDEM_AT_2008_508&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x06, 0)
DECL|macro|ZORRO_PROD_BSC_ALFA_RAM_1200
mdefine_line|#define  ZORRO_PROD_BSC_ALFA_RAM_1200&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x07, 0)
DECL|macro|ZORRO_PROD_BSC_OKTAGON_2008_RAM
mdefine_line|#define  ZORRO_PROD_BSC_OKTAGON_2008_RAM&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x08, 0)
DECL|macro|ZORRO_PROD_BSC_MULTIFACE_I
mdefine_line|#define  ZORRO_PROD_BSC_MULTIFACE_I&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x10, 0)
DECL|macro|ZORRO_PROD_BSC_MULTIFACE_II
mdefine_line|#define  ZORRO_PROD_BSC_MULTIFACE_II&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x11, 0)
DECL|macro|ZORRO_PROD_BSC_MULTIFACE_III
mdefine_line|#define  ZORRO_PROD_BSC_MULTIFACE_III&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x12, 0)
DECL|macro|ZORRO_PROD_BSC_FRAMEMASTER_II
mdefine_line|#define  ZORRO_PROD_BSC_FRAMEMASTER_II&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x20, 0)
DECL|macro|ZORRO_PROD_BSC_GRAFFITI_RAM
mdefine_line|#define  ZORRO_PROD_BSC_GRAFFITI_RAM&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x21, 0)
DECL|macro|ZORRO_PROD_BSC_GRAFFITI_REG
mdefine_line|#define  ZORRO_PROD_BSC_GRAFFITI_REG&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x22, 0)
DECL|macro|ZORRO_PROD_BSC_ISDN_MASTERCARD
mdefine_line|#define  ZORRO_PROD_BSC_ISDN_MASTERCARD&t;&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x40, 0)
DECL|macro|ZORRO_PROD_BSC_ISDN_MASTERCARD_II
mdefine_line|#define  ZORRO_PROD_BSC_ISDN_MASTERCARD_II&t;&t;&t;ZORRO_ID(BSC_ALFADATA_3, 0x41, 0)
DECL|macro|ZORRO_MANUF_PHOENIX
mdefine_line|#define ZORRO_MANUF_PHOENIX&t;&t;&t;&t;&t;0x0835
DECL|macro|ZORRO_PROD_PHOENIX_ST506
mdefine_line|#define  ZORRO_PROD_PHOENIX_ST506&t;&t;&t;&t;ZORRO_ID(PHOENIX, 0x21, 0)
DECL|macro|ZORRO_PROD_PHOENIX_SCSI
mdefine_line|#define  ZORRO_PROD_PHOENIX_SCSI&t;&t;&t;&t;ZORRO_ID(PHOENIX, 0x22, 0)
DECL|macro|ZORRO_PROD_PHOENIX_RAM
mdefine_line|#define  ZORRO_PROD_PHOENIX_RAM&t;&t;&t;&t;&t;ZORRO_ID(PHOENIX, 0xBE, 0)
DECL|macro|ZORRO_MANUF_ADVANCED_STORAGE_SYSTEMS
mdefine_line|#define ZORRO_MANUF_ADVANCED_STORAGE_SYSTEMS&t;&t;&t;0x0836
DECL|macro|ZORRO_PROD_ADVANCED_STORAGE_SYSTEMS_NEXUS
mdefine_line|#define  ZORRO_PROD_ADVANCED_STORAGE_SYSTEMS_NEXUS&t;&t;ZORRO_ID(ADVANCED_STORAGE_SYSTEMS, 0x01, 0)
DECL|macro|ZORRO_PROD_ADVANCED_STORAGE_SYSTEMS_NEXUS_RAM
mdefine_line|#define  ZORRO_PROD_ADVANCED_STORAGE_SYSTEMS_NEXUS_RAM&t;&t;ZORRO_ID(ADVANCED_STORAGE_SYSTEMS, 0x08, 0)
DECL|macro|ZORRO_MANUF_IMPULSE
mdefine_line|#define ZORRO_MANUF_IMPULSE&t;&t;&t;&t;&t;0x0838
DECL|macro|ZORRO_PROD_IMPULSE_FIRECRACKER_24
mdefine_line|#define  ZORRO_PROD_IMPULSE_FIRECRACKER_24&t;&t;&t;ZORRO_ID(IMPULSE, 0x00, 0)
DECL|macro|ZORRO_MANUF_IVS
mdefine_line|#define ZORRO_MANUF_IVS&t;&t;&t;&t;&t;&t;0x0840
DECL|macro|ZORRO_PROD_IVS_GRANDSLAM_PIC_2
mdefine_line|#define  ZORRO_PROD_IVS_GRANDSLAM_PIC_2&t;&t;&t;&t;ZORRO_ID(IVS, 0x02, 0)
DECL|macro|ZORRO_PROD_IVS_GRANDSLAM_PIC_1
mdefine_line|#define  ZORRO_PROD_IVS_GRANDSLAM_PIC_1&t;&t;&t;&t;ZORRO_ID(IVS, 0x04, 0)
DECL|macro|ZORRO_PROD_IVS_OVERDRIVE
mdefine_line|#define  ZORRO_PROD_IVS_OVERDRIVE&t;&t;&t;&t;ZORRO_ID(IVS, 0x10, 0)
DECL|macro|ZORRO_PROD_IVS_TRUMPCARD_CLASSIC
mdefine_line|#define  ZORRO_PROD_IVS_TRUMPCARD_CLASSIC&t;&t;&t;ZORRO_ID(IVS, 0x30, 0)
DECL|macro|ZORRO_PROD_IVS_TRUMPCARD_PRO_GRANDSLAM
mdefine_line|#define  ZORRO_PROD_IVS_TRUMPCARD_PRO_GRANDSLAM&t;&t;&t;ZORRO_ID(IVS, 0x34, 0)
DECL|macro|ZORRO_PROD_IVS_META_4
mdefine_line|#define  ZORRO_PROD_IVS_META_4&t;&t;&t;&t;&t;ZORRO_ID(IVS, 0x40, 0)
DECL|macro|ZORRO_PROD_IVS_WAVETOOLS
mdefine_line|#define  ZORRO_PROD_IVS_WAVETOOLS&t;&t;&t;&t;ZORRO_ID(IVS, 0xBF, 0)
DECL|macro|ZORRO_PROD_IVS_VECTOR_1
mdefine_line|#define  ZORRO_PROD_IVS_VECTOR_1&t;&t;&t;&t;ZORRO_ID(IVS, 0xF3, 0)
DECL|macro|ZORRO_PROD_IVS_VECTOR_2
mdefine_line|#define  ZORRO_PROD_IVS_VECTOR_2&t;&t;&t;&t;ZORRO_ID(IVS, 0xF4, 0)
DECL|macro|ZORRO_MANUF_VECTOR_1
mdefine_line|#define ZORRO_MANUF_VECTOR_1&t;&t;&t;&t;&t;0x0841
DECL|macro|ZORRO_PROD_VECTOR_CONNECTION_1
mdefine_line|#define  ZORRO_PROD_VECTOR_CONNECTION_1&t;&t;&t;&t;ZORRO_ID(VECTOR_1, 0xE3, 0)
DECL|macro|ZORRO_MANUF_XPERT_PRODEV
mdefine_line|#define ZORRO_MANUF_XPERT_PRODEV&t;&t;&t;&t;0x0845
DECL|macro|ZORRO_PROD_XPERT_PRODEV_VISIONA_RAM
mdefine_line|#define  ZORRO_PROD_XPERT_PRODEV_VISIONA_RAM&t;&t;&t;ZORRO_ID(XPERT_PRODEV, 0x01, 0)
DECL|macro|ZORRO_PROD_XPERT_PRODEV_VISIONA_REG
mdefine_line|#define  ZORRO_PROD_XPERT_PRODEV_VISIONA_REG&t;&t;&t;ZORRO_ID(XPERT_PRODEV, 0x02, 0)
DECL|macro|ZORRO_PROD_XPERT_PRODEV_MERLIN_RAM
mdefine_line|#define  ZORRO_PROD_XPERT_PRODEV_MERLIN_RAM&t;&t;&t;ZORRO_ID(XPERT_PRODEV, 0x03, 0)
DECL|macro|ZORRO_PROD_XPERT_PRODEV_MERLIN_REG_1
mdefine_line|#define  ZORRO_PROD_XPERT_PRODEV_MERLIN_REG_1&t;&t;&t;ZORRO_ID(XPERT_PRODEV, 0x04, 0)
DECL|macro|ZORRO_PROD_XPERT_PRODEV_MERLIN_REG_2
mdefine_line|#define  ZORRO_PROD_XPERT_PRODEV_MERLIN_REG_2&t;&t;&t;ZORRO_ID(XPERT_PRODEV, 0xC9, 0)
DECL|macro|ZORRO_MANUF_HYDRA_SYSTEMS
mdefine_line|#define ZORRO_MANUF_HYDRA_SYSTEMS&t;&t;&t;&t;0x0849
DECL|macro|ZORRO_PROD_HYDRA_SYSTEMS_AMIGANET
mdefine_line|#define  ZORRO_PROD_HYDRA_SYSTEMS_AMIGANET&t;&t;&t;ZORRO_ID(HYDRA_SYSTEMS, 0x01, 0)
DECL|macro|ZORRO_MANUF_SUNRIZE_INDUSTRIES
mdefine_line|#define ZORRO_MANUF_SUNRIZE_INDUSTRIES&t;&t;&t;&t;0x084F
DECL|macro|ZORRO_PROD_SUNRIZE_INDUSTRIES_AD1012
mdefine_line|#define  ZORRO_PROD_SUNRIZE_INDUSTRIES_AD1012&t;&t;&t;ZORRO_ID(SUNRIZE_INDUSTRIES, 0x01, 0)
DECL|macro|ZORRO_PROD_SUNRIZE_INDUSTRIES_AD516
mdefine_line|#define  ZORRO_PROD_SUNRIZE_INDUSTRIES_AD516&t;&t;&t;ZORRO_ID(SUNRIZE_INDUSTRIES, 0x02, 0)
DECL|macro|ZORRO_PROD_SUNRIZE_INDUSTRIES_DD512
mdefine_line|#define  ZORRO_PROD_SUNRIZE_INDUSTRIES_DD512&t;&t;&t;ZORRO_ID(SUNRIZE_INDUSTRIES, 0x03, 0)
DECL|macro|ZORRO_MANUF_TRICERATOPS
mdefine_line|#define ZORRO_MANUF_TRICERATOPS&t;&t;&t;&t;&t;0x0850
DECL|macro|ZORRO_PROD_TRICERATOPS_MULTI_IO
mdefine_line|#define  ZORRO_PROD_TRICERATOPS_MULTI_IO&t;&t;&t;ZORRO_ID(TRICERATOPS, 0x01, 0)
DECL|macro|ZORRO_MANUF_APPLIED_MAGIC
mdefine_line|#define ZORRO_MANUF_APPLIED_MAGIC&t;&t;&t;&t;0x0851
DECL|macro|ZORRO_PROD_APPLIED_MAGIC_DMI_RESOLVER
mdefine_line|#define  ZORRO_PROD_APPLIED_MAGIC_DMI_RESOLVER&t;&t;&t;ZORRO_ID(APPLIED_MAGIC, 0x01, 0)
DECL|macro|ZORRO_PROD_APPLIED_MAGIC_DIGITAL_BROADCASTER
mdefine_line|#define  ZORRO_PROD_APPLIED_MAGIC_DIGITAL_BROADCASTER&t;&t;ZORRO_ID(APPLIED_MAGIC, 0x06, 0)
DECL|macro|ZORRO_MANUF_GFX_BASE
mdefine_line|#define ZORRO_MANUF_GFX_BASE&t;&t;&t;&t;&t;0x085E
DECL|macro|ZORRO_PROD_GFX_BASE_GDA_1_VRAM
mdefine_line|#define  ZORRO_PROD_GFX_BASE_GDA_1_VRAM&t;&t;&t;&t;ZORRO_ID(GFX_BASE, 0x00, 0)
DECL|macro|ZORRO_PROD_GFX_BASE_GDA_1
mdefine_line|#define  ZORRO_PROD_GFX_BASE_GDA_1&t;&t;&t;&t;ZORRO_ID(GFX_BASE, 0x01, 0)
DECL|macro|ZORRO_MANUF_ROCTEC
mdefine_line|#define ZORRO_MANUF_ROCTEC&t;&t;&t;&t;&t;0x0860
DECL|macro|ZORRO_PROD_ROCTEC_RH_800C
mdefine_line|#define  ZORRO_PROD_ROCTEC_RH_800C&t;&t;&t;&t;ZORRO_ID(ROCTEC, 0x01, 0)
DECL|macro|ZORRO_PROD_ROCTEC_RH_800C_RAM
mdefine_line|#define  ZORRO_PROD_ROCTEC_RH_800C_RAM&t;&t;&t;&t;ZORRO_ID(ROCTEC, 0x01, 0)
DECL|macro|ZORRO_MANUF_KATO
mdefine_line|#define ZORRO_MANUF_KATO&t;&t;&t;&t;&t;0x0861
DECL|macro|ZORRO_PROD_KATO_MELODY
mdefine_line|#define  ZORRO_PROD_KATO_MELODY&t;&t;&t;&t;&t;ZORRO_ID(KATO, 0x80, 0)
multiline_comment|/* ID clash!! */
DECL|macro|ZORRO_MANUF_HELFRICH_1
mdefine_line|#define ZORRO_MANUF_HELFRICH_1&t;&t;&t;&t;&t;0x0861
DECL|macro|ZORRO_PROD_HELFRICH_RAINBOW_II
mdefine_line|#define  ZORRO_PROD_HELFRICH_RAINBOW_II&t;&t;&t;&t;ZORRO_ID(HELFRICH_1, 0x20, 0)
DECL|macro|ZORRO_PROD_HELFRICH_RAINBOW_III
mdefine_line|#define  ZORRO_PROD_HELFRICH_RAINBOW_III&t;&t;&t;ZORRO_ID(HELFRICH_1, 0x21, 0)
DECL|macro|ZORRO_MANUF_ATLANTIS
mdefine_line|#define ZORRO_MANUF_ATLANTIS&t;&t;&t;&t;&t;0x0862
DECL|macro|ZORRO_MANUF_PROTAR
mdefine_line|#define ZORRO_MANUF_PROTAR&t;&t;&t;&t;&t;0x0864
DECL|macro|ZORRO_MANUF_ACS
mdefine_line|#define ZORRO_MANUF_ACS&t;&t;&t;&t;&t;&t;0x0865
DECL|macro|ZORRO_MANUF_SOFTWARE_RESULTS_ENTERPRISES
mdefine_line|#define ZORRO_MANUF_SOFTWARE_RESULTS_ENTERPRISES&t;&t;0x0866
DECL|macro|ZORRO_PROD_SOFTWARE_RESULTS_ENTERPRISES_GOLDEN_GATE_2_BUS_PLUS
mdefine_line|#define  ZORRO_PROD_SOFTWARE_RESULTS_ENTERPRISES_GOLDEN_GATE_2_BUS_PLUS&t;ZORRO_ID(SOFTWARE_RESULTS_ENTERPRISES, 0x01, 0)
DECL|macro|ZORRO_MANUF_MASOBOSHI
mdefine_line|#define ZORRO_MANUF_MASOBOSHI&t;&t;&t;&t;&t;0x086D
DECL|macro|ZORRO_PROD_MASOBOSHI_MASTER_CARD_SC201
mdefine_line|#define  ZORRO_PROD_MASOBOSHI_MASTER_CARD_SC201&t;&t;&t;ZORRO_ID(MASOBOSHI, 0x03, 0)
DECL|macro|ZORRO_PROD_MASOBOSHI_MASTER_CARD_MC702
mdefine_line|#define  ZORRO_PROD_MASOBOSHI_MASTER_CARD_MC702&t;&t;&t;ZORRO_ID(MASOBOSHI, 0x04, 0)
DECL|macro|ZORRO_PROD_MASOBOSHI_MVD_819
mdefine_line|#define  ZORRO_PROD_MASOBOSHI_MVD_819&t;&t;&t;&t;ZORRO_ID(MASOBOSHI, 0x07, 0)
DECL|macro|ZORRO_MANUF_MAINHATTAN_DATA
mdefine_line|#define ZORRO_MANUF_MAINHATTAN_DATA&t;&t;&t;&t;0x086F
DECL|macro|ZORRO_PROD_MAINHATTAN_DATA_IDE
mdefine_line|#define  ZORRO_PROD_MAINHATTAN_DATA_IDE&t;&t;&t;&t;ZORRO_ID(MAINHATTAN_DATA, 0x01, 0)
DECL|macro|ZORRO_MANUF_VILLAGE_TRONIC
mdefine_line|#define ZORRO_MANUF_VILLAGE_TRONIC&t;&t;&t;&t;0x0877
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_DOMINO_RAM
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_DOMINO_RAM&t;&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0x01, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_DOMINO_REG
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_DOMINO_REG&t;&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0x02, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_DOMINO_16M_PROTOTYPE
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_DOMINO_16M_PROTOTYPE&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0x03, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_PICASSO_II_II_PLUS_RAM
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_PICASSO_II_II_PLUS_RAM&t;ZORRO_ID(VILLAGE_TRONIC, 0x0B, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_PICASSO_II_II_PLUS_REG
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_PICASSO_II_II_PLUS_REG&t;ZORRO_ID(VILLAGE_TRONIC, 0x0C, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_PICASSO_II_II_PLUS_SEGMENTED_MODE
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_PICASSO_II_II_PLUS_SEGMENTED_MODE&t;ZORRO_ID(VILLAGE_TRONIC, 0x0D, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z2_MEM1
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z2_MEM1&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0x15, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z2_MEM2
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z2_MEM2&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0x16, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z2_REG
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z2_REG&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0x17, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z3
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_PICASSO_IV_Z3&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0x18, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_ARIADNE
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_ARIADNE&t;&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0xC9, 0)
DECL|macro|ZORRO_PROD_VILLAGE_TRONIC_ARIADNE2
mdefine_line|#define  ZORRO_PROD_VILLAGE_TRONIC_ARIADNE2&t;&t;&t;ZORRO_ID(VILLAGE_TRONIC, 0xCA, 0)
DECL|macro|ZORRO_MANUF_UTILITIES_UNLIMITED
mdefine_line|#define ZORRO_MANUF_UTILITIES_UNLIMITED&t;&t;&t;&t;0x087B
DECL|macro|ZORRO_PROD_UTILITIES_UNLIMITED_EMPLANT_DELUXE
mdefine_line|#define  ZORRO_PROD_UTILITIES_UNLIMITED_EMPLANT_DELUXE&t;&t;ZORRO_ID(UTILITIES_UNLIMITED, 0x15, 0)
DECL|macro|ZORRO_PROD_UTILITIES_UNLIMITED_EMPLANT_DELUXE2
mdefine_line|#define  ZORRO_PROD_UTILITIES_UNLIMITED_EMPLANT_DELUXE2&t;&t;ZORRO_ID(UTILITIES_UNLIMITED, 0x20, 0)
DECL|macro|ZORRO_MANUF_AMITRIX
mdefine_line|#define ZORRO_MANUF_AMITRIX&t;&t;&t;&t;&t;0x0880
DECL|macro|ZORRO_PROD_AMITRIX_MULTI_IO
mdefine_line|#define  ZORRO_PROD_AMITRIX_MULTI_IO&t;&t;&t;&t;ZORRO_ID(AMITRIX, 0x01, 0)
DECL|macro|ZORRO_PROD_AMITRIX_CD_RAM
mdefine_line|#define  ZORRO_PROD_AMITRIX_CD_RAM&t;&t;&t;&t;ZORRO_ID(AMITRIX, 0x02, 0)
DECL|macro|ZORRO_MANUF_ARMAX
mdefine_line|#define ZORRO_MANUF_ARMAX&t;&t;&t;&t;&t;0x0885
DECL|macro|ZORRO_PROD_ARMAX_OMNIBUS
mdefine_line|#define  ZORRO_PROD_ARMAX_OMNIBUS&t;&t;&t;&t;ZORRO_ID(ARMAX, 0x00, 0)
DECL|macro|ZORRO_MANUF_ZEUS
mdefine_line|#define ZORRO_MANUF_ZEUS&t;&t;&t;&t;&t;0x088D
DECL|macro|ZORRO_PROD_ZEUS_SPIDER
mdefine_line|#define  ZORRO_PROD_ZEUS_SPIDER&t;&t;&t;&t;&t;ZORRO_ID(ZEUS, 0x04, 0)
DECL|macro|ZORRO_MANUF_NEWTEK
mdefine_line|#define ZORRO_MANUF_NEWTEK&t;&t;&t;&t;&t;0x088F
DECL|macro|ZORRO_PROD_NEWTEK_VIDEOTOASTER
mdefine_line|#define  ZORRO_PROD_NEWTEK_VIDEOTOASTER&t;&t;&t;&t;ZORRO_ID(NEWTEK, 0x00, 0)
DECL|macro|ZORRO_MANUF_M_TECH_GERMANY
mdefine_line|#define ZORRO_MANUF_M_TECH_GERMANY&t;&t;&t;&t;0x0890
DECL|macro|ZORRO_PROD_MTEC_AT500_2
mdefine_line|#define  ZORRO_PROD_MTEC_AT500_2&t;&t;&t;&t;ZORRO_ID(M_TECH_GERMANY, 0x01, 0)
DECL|macro|ZORRO_PROD_MTEC_68030
mdefine_line|#define  ZORRO_PROD_MTEC_68030&t;&t;&t;&t;&t;ZORRO_ID(M_TECH_GERMANY, 0x03, 0)
DECL|macro|ZORRO_PROD_MTEC_68020I
mdefine_line|#define  ZORRO_PROD_MTEC_68020I&t;&t;&t;&t;&t;ZORRO_ID(M_TECH_GERMANY, 0x06, 0)
DECL|macro|ZORRO_PROD_MTEC_A1200_T68030_RTC
mdefine_line|#define  ZORRO_PROD_MTEC_A1200_T68030_RTC&t;&t;&t;ZORRO_ID(M_TECH_GERMANY, 0x20, 0)
DECL|macro|ZORRO_PROD_MTEC_VIPER_MK_V_E_MATRIX_530
mdefine_line|#define  ZORRO_PROD_MTEC_VIPER_MK_V_E_MATRIX_530&t;&t;ZORRO_ID(M_TECH_GERMANY, 0x21, 0)
DECL|macro|ZORRO_PROD_MTEC_8_MB_RAM
mdefine_line|#define  ZORRO_PROD_MTEC_8_MB_RAM&t;&t;&t;&t;ZORRO_ID(M_TECH_GERMANY, 0x22, 0)
DECL|macro|ZORRO_PROD_MTEC_VIPER_MK_V_E_MATRIX_530_SCSI_IDE
mdefine_line|#define  ZORRO_PROD_MTEC_VIPER_MK_V_E_MATRIX_530_SCSI_IDE&t;ZORRO_ID(M_TECH_GERMANY, 0x24, 0)
DECL|macro|ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_4
mdefine_line|#define ZORRO_MANUF_GREAT_VALLEY_PRODUCTS_4&t;&t;&t;0x0891
DECL|macro|ZORRO_PROD_GVP_EGS_28_24_SPECTRUM_RAM
mdefine_line|#define  ZORRO_PROD_GVP_EGS_28_24_SPECTRUM_RAM&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_4, 0x01, 0)
DECL|macro|ZORRO_PROD_GVP_EGS_28_24_SPECTRUM_REG
mdefine_line|#define  ZORRO_PROD_GVP_EGS_28_24_SPECTRUM_REG&t;&t;&t;ZORRO_ID(GREAT_VALLEY_PRODUCTS_4, 0x02, 0)
DECL|macro|ZORRO_MANUF_APOLLO_1
mdefine_line|#define ZORRO_MANUF_APOLLO_1&t;&t;&t;&t;&t;0x0892
DECL|macro|ZORRO_PROD_APOLLO_A1200
mdefine_line|#define  ZORRO_PROD_APOLLO_A1200&t;&t;&t;&t;ZORRO_ID(APOLLO_1, 0x01, 0)
DECL|macro|ZORRO_MANUF_HELFRICH_2
mdefine_line|#define ZORRO_MANUF_HELFRICH_2&t;&t;&t;&t;&t;0x0893
DECL|macro|ZORRO_PROD_HELFRICH_PICCOLO_RAM
mdefine_line|#define  ZORRO_PROD_HELFRICH_PICCOLO_RAM&t;&t;&t;ZORRO_ID(HELFRICH_2, 0x05, 0)
DECL|macro|ZORRO_PROD_HELFRICH_PICCOLO_REG
mdefine_line|#define  ZORRO_PROD_HELFRICH_PICCOLO_REG&t;&t;&t;ZORRO_ID(HELFRICH_2, 0x06, 0)
DECL|macro|ZORRO_PROD_HELFRICH_PEGGY_PLUS_MPEG
mdefine_line|#define  ZORRO_PROD_HELFRICH_PEGGY_PLUS_MPEG&t;&t;&t;ZORRO_ID(HELFRICH_2, 0x07, 0)
DECL|macro|ZORRO_PROD_HELFRICH_VIDEOCRUNCHER
mdefine_line|#define  ZORRO_PROD_HELFRICH_VIDEOCRUNCHER&t;&t;&t;ZORRO_ID(HELFRICH_2, 0x08, 0)
DECL|macro|ZORRO_PROD_HELFRICH_SD64_RAM
mdefine_line|#define  ZORRO_PROD_HELFRICH_SD64_RAM&t;&t;&t;&t;ZORRO_ID(HELFRICH_2, 0x0A, 0)
DECL|macro|ZORRO_PROD_HELFRICH_SD64_REG
mdefine_line|#define  ZORRO_PROD_HELFRICH_SD64_REG&t;&t;&t;&t;ZORRO_ID(HELFRICH_2, 0x0B, 0)
DECL|macro|ZORRO_MANUF_MACROSYSTEMS_USA
mdefine_line|#define ZORRO_MANUF_MACROSYSTEMS_USA&t;&t;&t;&t;0x089B
DECL|macro|ZORRO_PROD_MACROSYSTEMS_WARP_ENGINE_40xx
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_WARP_ENGINE_40xx&t;&t;ZORRO_ID(MACROSYSTEMS_USA, 0x13, 0)
DECL|macro|ZORRO_MANUF_ELBOX_COMPUTER
mdefine_line|#define ZORRO_MANUF_ELBOX_COMPUTER&t;&t;&t;&t;0x089E
DECL|macro|ZORRO_PROD_ELBOX_COMPUTER_1200_4
mdefine_line|#define  ZORRO_PROD_ELBOX_COMPUTER_1200_4&t;&t;&t;ZORRO_ID(ELBOX_COMPUTER, 0x06, 0)
DECL|macro|ZORRO_MANUF_HARMS_PROFESSIONAL
mdefine_line|#define ZORRO_MANUF_HARMS_PROFESSIONAL&t;&t;&t;&t;0x0A00
DECL|macro|ZORRO_PROD_HARMS_PROFESSIONAL_030_PLUS
mdefine_line|#define  ZORRO_PROD_HARMS_PROFESSIONAL_030_PLUS&t;&t;&t;ZORRO_ID(HARMS_PROFESSIONAL, 0x10, 0)
DECL|macro|ZORRO_PROD_HARMS_PROFESSIONAL_3500
mdefine_line|#define  ZORRO_PROD_HARMS_PROFESSIONAL_3500&t;&t;&t;ZORRO_ID(HARMS_PROFESSIONAL, 0xD0, 0)
DECL|macro|ZORRO_MANUF_MICRONIK
mdefine_line|#define ZORRO_MANUF_MICRONIK&t;&t;&t;&t;&t;0x0A50
DECL|macro|ZORRO_PROD_MICRONIK_RCA_120
mdefine_line|#define  ZORRO_PROD_MICRONIK_RCA_120&t;&t;&t;&t;ZORRO_ID(MICRONIK, 0x0A, 0)
DECL|macro|ZORRO_MANUF_MICRONIK2
mdefine_line|#define ZORRO_MANUF_MICRONIK2&t;&t;&t;&t;&t;0x0F0F
DECL|macro|ZORRO_PROD_MICRONIK2_Z3I
mdefine_line|#define  ZORRO_PROD_MICRONIK2_Z3I&t;&t;&t;&t;ZORRO_ID(MICRONIK2, 0x01, 0)
DECL|macro|ZORRO_MANUF_MEGAMICRO
mdefine_line|#define ZORRO_MANUF_MEGAMICRO&t;&t;&t;&t;&t;0x1000
DECL|macro|ZORRO_PROD_MEGAMICRO_SCRAM_500
mdefine_line|#define  ZORRO_PROD_MEGAMICRO_SCRAM_500&t;&t;&t;&t;ZORRO_ID(MEGAMICRO, 0x03, 0)
DECL|macro|ZORRO_PROD_MEGAMICRO_SCRAM_500_RAM
mdefine_line|#define  ZORRO_PROD_MEGAMICRO_SCRAM_500_RAM&t;&t;&t;ZORRO_ID(MEGAMICRO, 0x04, 0)
DECL|macro|ZORRO_MANUF_IMTRONICS_2
mdefine_line|#define ZORRO_MANUF_IMTRONICS_2&t;&t;&t;&t;&t;0x1028
DECL|macro|ZORRO_PROD_IMTRONICS_HURRICANE_2800_3
mdefine_line|#define  ZORRO_PROD_IMTRONICS_HURRICANE_2800_3&t;&t;&t;ZORRO_ID(IMTRONICS_2, 0x39, 0)
DECL|macro|ZORRO_PROD_IMTRONICS_HURRICANE_2800_4
mdefine_line|#define  ZORRO_PROD_IMTRONICS_HURRICANE_2800_4&t;&t;&t;ZORRO_ID(IMTRONICS_2, 0x57, 0)
multiline_comment|/* unofficial ID */
DECL|macro|ZORRO_MANUF_INDIVIDUAL_COMPUTERS
mdefine_line|#define ZORRO_MANUF_INDIVIDUAL_COMPUTERS&t;&t;&t;0x1212
DECL|macro|ZORRO_PROD_INDIVIDUAL_COMPUTERS_BUDDHA
mdefine_line|#define  ZORRO_PROD_INDIVIDUAL_COMPUTERS_BUDDHA&t;&t;&t;ZORRO_ID(INDIVIDUAL_COMPUTERS, 0x00, 0)
DECL|macro|ZORRO_PROD_INDIVIDUAL_COMPUTERS_X_SURF
mdefine_line|#define  ZORRO_PROD_INDIVIDUAL_COMPUTERS_X_SURF&t;&t;&t;ZORRO_ID(INDIVIDUAL_COMPUTERS, 0x17, 0)
DECL|macro|ZORRO_PROD_INDIVIDUAL_COMPUTERS_CATWEASEL
mdefine_line|#define  ZORRO_PROD_INDIVIDUAL_COMPUTERS_CATWEASEL&t;&t;ZORRO_ID(INDIVIDUAL_COMPUTERS, 0x2A, 0)
DECL|macro|ZORRO_MANUF_KUPKE_3
mdefine_line|#define ZORRO_MANUF_KUPKE_3&t;&t;&t;&t;&t;0x1248
DECL|macro|ZORRO_PROD_KUPKE_GOLEM_HD_3000
mdefine_line|#define  ZORRO_PROD_KUPKE_GOLEM_HD_3000&t;&t;&t;&t;ZORRO_ID(KUPKE_3, 0x01, 0)
DECL|macro|ZORRO_MANUF_ITH
mdefine_line|#define ZORRO_MANUF_ITH&t;&t;&t;&t;&t;&t;0x1388
DECL|macro|ZORRO_PROD_ITH_ISDN_MASTER_II
mdefine_line|#define  ZORRO_PROD_ITH_ISDN_MASTER_II&t;&t;&t;&t;ZORRO_ID(ITH, 0x01, 0)
DECL|macro|ZORRO_MANUF_VMC
mdefine_line|#define ZORRO_MANUF_VMC&t;&t;&t;&t;&t;&t;0x1389
DECL|macro|ZORRO_PROD_VMC_ISDN_BLASTER_Z2
mdefine_line|#define  ZORRO_PROD_VMC_ISDN_BLASTER_Z2&t;&t;&t;&t;ZORRO_ID(VMC, 0x01, 0)
DECL|macro|ZORRO_PROD_VMC_HYPERCOM_4
mdefine_line|#define  ZORRO_PROD_VMC_HYPERCOM_4&t;&t;&t;&t;ZORRO_ID(VMC, 0x02, 0)
DECL|macro|ZORRO_MANUF_INFORMATION
mdefine_line|#define ZORRO_MANUF_INFORMATION&t;&t;&t;&t;&t;0x157C
DECL|macro|ZORRO_PROD_INFORMATION_ISDN_ENGINE_I
mdefine_line|#define  ZORRO_PROD_INFORMATION_ISDN_ENGINE_I&t;&t;&t;ZORRO_ID(INFORMATION, 0x64, 0)
DECL|macro|ZORRO_MANUF_VORTEX
mdefine_line|#define ZORRO_MANUF_VORTEX&t;&t;&t;&t;&t;0x2017
DECL|macro|ZORRO_PROD_VORTEX_GOLDEN_GATE_80386SX
mdefine_line|#define  ZORRO_PROD_VORTEX_GOLDEN_GATE_80386SX&t;&t;&t;ZORRO_ID(VORTEX, 0x07, 0)
DECL|macro|ZORRO_PROD_VORTEX_GOLDEN_GATE_RAM
mdefine_line|#define  ZORRO_PROD_VORTEX_GOLDEN_GATE_RAM&t;&t;&t;ZORRO_ID(VORTEX, 0x08, 0)
DECL|macro|ZORRO_PROD_VORTEX_GOLDEN_GATE_80486
mdefine_line|#define  ZORRO_PROD_VORTEX_GOLDEN_GATE_80486&t;&t;&t;ZORRO_ID(VORTEX, 0x09, 0)
DECL|macro|ZORRO_MANUF_EXPANSION_SYSTEMS
mdefine_line|#define ZORRO_MANUF_EXPANSION_SYSTEMS&t;&t;&t;&t;0x2062
DECL|macro|ZORRO_PROD_EXPANSION_SYSTEMS_DATAFLYER_4000SX
mdefine_line|#define  ZORRO_PROD_EXPANSION_SYSTEMS_DATAFLYER_4000SX&t;&t;ZORRO_ID(EXPANSION_SYSTEMS, 0x01, 0)
DECL|macro|ZORRO_PROD_EXPANSION_SYSTEMS_DATAFLYER_4000SX_RAM
mdefine_line|#define  ZORRO_PROD_EXPANSION_SYSTEMS_DATAFLYER_4000SX_RAM&t;ZORRO_ID(EXPANSION_SYSTEMS, 0x02, 0)
DECL|macro|ZORRO_MANUF_READYSOFT
mdefine_line|#define ZORRO_MANUF_READYSOFT&t;&t;&t;&t;&t;0x2100
DECL|macro|ZORRO_PROD_READYSOFT_AMAX_II_IV
mdefine_line|#define  ZORRO_PROD_READYSOFT_AMAX_II_IV&t;&t;&t;ZORRO_ID(READYSOFT, 0x01, 0)
DECL|macro|ZORRO_MANUF_PHASE5
mdefine_line|#define ZORRO_MANUF_PHASE5&t;&t;&t;&t;&t;0x2140
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_RAM
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_RAM&t;&t;&t;&t;ZORRO_ID(PHASE5, 0x01, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD&t;&t;&t;&t;ZORRO_ID(PHASE5, 0x02, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_1220_IV
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_1220_IV&t;&t;&t;ZORRO_ID(PHASE5, 0x06, 0)
DECL|macro|ZORRO_PROD_PHASE5_FASTLANE_Z3_RAM
mdefine_line|#define  ZORRO_PROD_PHASE5_FASTLANE_Z3_RAM&t;&t;&t;ZORRO_ID(PHASE5, 0x0A, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_1230_II_FASTLANE_Z3_CYBERSCSI_CYBERSTORM060
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_1230_II_FASTLANE_Z3_CYBERSCSI_CYBERSTORM060&t;ZORRO_ID(PHASE5, 0x0B, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_1220_CYBERSTORM
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_1220_CYBERSTORM&t;&t;ZORRO_ID(PHASE5, 0x0C, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_1230
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_1230&t;&t;&t;ZORRO_ID(PHASE5, 0x0D, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_1230_IV_1260
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_1230_IV_1260&t;&t;ZORRO_ID(PHASE5, 0x11, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_2060
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_2060&t;&t;&t;ZORRO_ID(PHASE5, 0x18, 0)
DECL|macro|ZORRO_PROD_PHASE5_CYBERSTORM_MK_II
mdefine_line|#define  ZORRO_PROD_PHASE5_CYBERSTORM_MK_II&t;&t;&t;ZORRO_ID(PHASE5, 0x19, 0)
DECL|macro|ZORRO_PROD_PHASE5_CYBERVISION64
mdefine_line|#define  ZORRO_PROD_PHASE5_CYBERVISION64&t;&t;&t;ZORRO_ID(PHASE5, 0x22, 0)
DECL|macro|ZORRO_PROD_PHASE5_CYBERVISION64_3D_PROTOTYPE
mdefine_line|#define  ZORRO_PROD_PHASE5_CYBERVISION64_3D_PROTOTYPE&t;&t;ZORRO_ID(PHASE5, 0x32, 0)
DECL|macro|ZORRO_PROD_PHASE5_CYBERVISION64_3D
mdefine_line|#define  ZORRO_PROD_PHASE5_CYBERVISION64_3D&t;&t;&t;ZORRO_ID(PHASE5, 0x43, 0)
DECL|macro|ZORRO_PROD_PHASE5_CYBERSTORM_MK_III
mdefine_line|#define  ZORRO_PROD_PHASE5_CYBERSTORM_MK_III&t;&t;&t;ZORRO_ID(PHASE5, 0x64, 0)
DECL|macro|ZORRO_PROD_PHASE5_BLIZZARD_603E_PLUS
mdefine_line|#define  ZORRO_PROD_PHASE5_BLIZZARD_603E_PLUS&t;&t;&t;ZORRO_ID(PHASE5, 0x6e, 0)
DECL|macro|ZORRO_MANUF_DPS
mdefine_line|#define ZORRO_MANUF_DPS&t;&t;&t;&t;&t;&t;0x2169
DECL|macro|ZORRO_PROD_DPS_PERSONAL_ANIMATION_RECORDER
mdefine_line|#define  ZORRO_PROD_DPS_PERSONAL_ANIMATION_RECORDER&t;&t;ZORRO_ID(DPS, 0x01, 0)
DECL|macro|ZORRO_MANUF_APOLLO_2
mdefine_line|#define ZORRO_MANUF_APOLLO_2&t;&t;&t;&t;&t;0x2200
DECL|macro|ZORRO_PROD_APOLLO_A620_68020_1
mdefine_line|#define  ZORRO_PROD_APOLLO_A620_68020_1&t;&t;&t;&t;ZORRO_ID(APOLLO_2, 0x00, 0)
DECL|macro|ZORRO_PROD_APOLLO_A620_68020_2
mdefine_line|#define  ZORRO_PROD_APOLLO_A620_68020_2&t;&t;&t;&t;ZORRO_ID(APOLLO_2, 0x01, 0)
DECL|macro|ZORRO_MANUF_APOLLO_3
mdefine_line|#define ZORRO_MANUF_APOLLO_3&t;&t;&t;&t;&t;0x2222
DECL|macro|ZORRO_PROD_APOLLO_AT_APOLLO
mdefine_line|#define  ZORRO_PROD_APOLLO_AT_APOLLO&t;&t;&t;&t;ZORRO_ID(APOLLO_3, 0x22, 0)
DECL|macro|ZORRO_PROD_APOLLO_1230_1240_1260_2030_4040_4060
mdefine_line|#define  ZORRO_PROD_APOLLO_1230_1240_1260_2030_4040_4060&t;ZORRO_ID(APOLLO_3, 0x23, 0)
DECL|macro|ZORRO_MANUF_PETSOFF_LP
mdefine_line|#define ZORRO_MANUF_PETSOFF_LP&t;&t;&t;&t;&t;0x38A5
DECL|macro|ZORRO_PROD_PETSOFF_LP_DELFINA
mdefine_line|#define  ZORRO_PROD_PETSOFF_LP_DELFINA&t;&t;&t;&t;ZORRO_ID(PETSOFF_LP, 0x00, 0)
DECL|macro|ZORRO_PROD_PETSOFF_LP_DELFINA_LITE
mdefine_line|#define  ZORRO_PROD_PETSOFF_LP_DELFINA_LITE&t;&t;&t;ZORRO_ID(PETSOFF_LP, 0x01, 0)
DECL|macro|ZORRO_MANUF_UWE_GERLACH
mdefine_line|#define ZORRO_MANUF_UWE_GERLACH&t;&t;&t;&t;&t;0x3FF7
DECL|macro|ZORRO_PROD_UWE_GERLACH_RAM_ROM
mdefine_line|#define  ZORRO_PROD_UWE_GERLACH_RAM_ROM&t;&t;&t;&t;ZORRO_ID(UWE_GERLACH, 0xd4, 0)
DECL|macro|ZORRO_MANUF_ACT
mdefine_line|#define ZORRO_MANUF_ACT&t;&t;&t;&t;&t;&t;0x4231
DECL|macro|ZORRO_PROD_ACT_PRELUDE
mdefine_line|#define  ZORRO_PROD_ACT_PRELUDE&t;&t;&t;&t;&t;ZORRO_ID(ACT, 0x01, 0)
DECL|macro|ZORRO_MANUF_MACROSYSTEMS_GERMANY
mdefine_line|#define ZORRO_MANUF_MACROSYSTEMS_GERMANY&t;&t;&t;0x4754
DECL|macro|ZORRO_PROD_MACROSYSTEMS_MAESTRO
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_MAESTRO&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x03, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_VLAB
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_VLAB&t;&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x04, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_MAESTRO_PRO
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_MAESTRO_PRO&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x05, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_RETINA
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_RETINA&t;&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x06, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_MULTI_EVOLUTION
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_MULTI_EVOLUTION&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x08, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_TOCCATA
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_TOCCATA&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x0C, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_RETINA_Z3
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_RETINA_Z3&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x10, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_VLAB_MOTION
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_VLAB_MOTION&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x12, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_ALTAIS
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_ALTAIS&t;&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0x13, 0)
DECL|macro|ZORRO_PROD_MACROSYSTEMS_FALCON_040
mdefine_line|#define  ZORRO_PROD_MACROSYSTEMS_FALCON_040&t;&t;&t;ZORRO_ID(MACROSYSTEMS_GERMANY, 0xFD, 0)
DECL|macro|ZORRO_MANUF_COMBITEC
mdefine_line|#define ZORRO_MANUF_COMBITEC&t;&t;&t;&t;&t;0x6766
DECL|macro|ZORRO_MANUF_SKI_PERIPHERALS
mdefine_line|#define ZORRO_MANUF_SKI_PERIPHERALS&t;&t;&t;&t;0x8000
DECL|macro|ZORRO_PROD_SKI_PERIPHERALS_MAST_FIREBALL
mdefine_line|#define  ZORRO_PROD_SKI_PERIPHERALS_MAST_FIREBALL&t;&t;ZORRO_ID(SKI_PERIPHERALS, 0x08, 0)
DECL|macro|ZORRO_PROD_SKI_PERIPHERALS_SCSI_DUAL_SERIAL
mdefine_line|#define  ZORRO_PROD_SKI_PERIPHERALS_SCSI_DUAL_SERIAL&t;&t;ZORRO_ID(SKI_PERIPHERALS, 0x80, 0)
DECL|macro|ZORRO_MANUF_REIS_WARE_2
mdefine_line|#define ZORRO_MANUF_REIS_WARE_2&t;&t;&t;&t;&t;0xA9AD
DECL|macro|ZORRO_PROD_REIS_WARE_SCAN_KING
mdefine_line|#define  ZORRO_PROD_REIS_WARE_SCAN_KING&t;&t;&t;&t;ZORRO_ID(REIS_WARE_2, 0x11, 0)
DECL|macro|ZORRO_MANUF_CAMERON
mdefine_line|#define ZORRO_MANUF_CAMERON&t;&t;&t;&t;&t;0xAA01
DECL|macro|ZORRO_PROD_CAMERON_PERSONAL_A4
mdefine_line|#define  ZORRO_PROD_CAMERON_PERSONAL_A4&t;&t;&t;&t;ZORRO_ID(CAMERON, 0x10, 0)
DECL|macro|ZORRO_MANUF_REIS_WARE
mdefine_line|#define ZORRO_MANUF_REIS_WARE&t;&t;&t;&t;&t;0xAA11
DECL|macro|ZORRO_PROD_REIS_WARE_HANDYSCANNER
mdefine_line|#define  ZORRO_PROD_REIS_WARE_HANDYSCANNER&t;&t;&t;ZORRO_ID(REIS_WARE, 0x11, 0)
DECL|macro|ZORRO_MANUF_PHOENIX_2
mdefine_line|#define ZORRO_MANUF_PHOENIX_2&t;&t;&t;&t;&t;0xB5A8
DECL|macro|ZORRO_PROD_PHOENIX_ST506_2
mdefine_line|#define  ZORRO_PROD_PHOENIX_ST506_2&t;&t;&t;&t;ZORRO_ID(PHOENIX_2, 0x21, 0)
DECL|macro|ZORRO_PROD_PHOENIX_SCSI_2
mdefine_line|#define  ZORRO_PROD_PHOENIX_SCSI_2&t;&t;&t;&t;ZORRO_ID(PHOENIX_2, 0x22, 0)
DECL|macro|ZORRO_PROD_PHOENIX_RAM_2
mdefine_line|#define  ZORRO_PROD_PHOENIX_RAM_2&t;&t;&t;&t;ZORRO_ID(PHOENIX_2, 0xBE, 0)
DECL|macro|ZORRO_MANUF_COMBITEC_2
mdefine_line|#define ZORRO_MANUF_COMBITEC_2&t;&t;&t;&t;&t;0xC008
DECL|macro|ZORRO_PROD_COMBITEC_HD
mdefine_line|#define  ZORRO_PROD_COMBITEC_HD&t;&t;&t;&t;&t;ZORRO_ID(COMBITEC_2, 0x2A, 0)
DECL|macro|ZORRO_PROD_COMBITEC_SRAM
mdefine_line|#define  ZORRO_PROD_COMBITEC_SRAM&t;&t;&t;&t;ZORRO_ID(COMBITEC_2, 0x2B, 0)
multiline_comment|/*&n;     *  Test and illegal Manufacturer IDs.&n;     */
DECL|macro|ZORRO_MANUF_HACKER
mdefine_line|#define ZORRO_MANUF_HACKER&t;&t;&t;&t;&t;0x07DB
DECL|macro|ZORRO_PROD_GENERAL_PROTOTYPE
mdefine_line|#define  ZORRO_PROD_GENERAL_PROTOTYPE&t;&t;&t;&t;ZORRO_ID(HACKER, 0x00, 0)
DECL|macro|ZORRO_PROD_HACKER_SCSI
mdefine_line|#define  ZORRO_PROD_HACKER_SCSI&t;&t;&t;&t;&t;ZORRO_ID(HACKER, 0x01, 0)
DECL|macro|ZORRO_PROD_RESOURCE_MANAGEMENT_FORCE_QUICKNET_QN2000
mdefine_line|#define  ZORRO_PROD_RESOURCE_MANAGEMENT_FORCE_QUICKNET_QN2000&t;ZORRO_ID(HACKER, 0x02, 0)
DECL|macro|ZORRO_PROD_VECTOR_CONNECTION_2
mdefine_line|#define  ZORRO_PROD_VECTOR_CONNECTION_2&t;&t;&t;&t;ZORRO_ID(HACKER, 0xE0, 0)
DECL|macro|ZORRO_PROD_VECTOR_CONNECTION_3
mdefine_line|#define  ZORRO_PROD_VECTOR_CONNECTION_3&t;&t;&t;&t;ZORRO_ID(HACKER, 0xE1, 0)
DECL|macro|ZORRO_PROD_VECTOR_CONNECTION_4
mdefine_line|#define  ZORRO_PROD_VECTOR_CONNECTION_4&t;&t;&t;&t;ZORRO_ID(HACKER, 0xE2, 0)
DECL|macro|ZORRO_PROD_VECTOR_CONNECTION_5
mdefine_line|#define  ZORRO_PROD_VECTOR_CONNECTION_5&t;&t;&t;&t;ZORRO_ID(HACKER, 0xE3, 0)
eof
