macro_line|#ifndef _ASMAXP_GENTRAP_H
DECL|macro|_ASMAXP_GENTRAP_H
mdefine_line|#define _ASMAXP_GENTRAP_H
multiline_comment|/*&n; * Definitions for gentrap causes.  They are generated by user-level&n; * programs and therefore should be compatible with the corresponding&n; * OSF/1 definitions.&n; */
DECL|macro|GEN_INTOVF
mdefine_line|#define GEN_INTOVF&t;-1&t;/* integer overflow */
DECL|macro|GEN_INTDIV
mdefine_line|#define GEN_INTDIV&t;-2&t;/* integer division by zero */
DECL|macro|GEN_FLTOVF
mdefine_line|#define GEN_FLTOVF&t;-3&t;/* fp overflow */
DECL|macro|GEN_FLTDIV
mdefine_line|#define GEN_FLTDIV&t;-4&t;/* fp division by zero */
DECL|macro|GEN_FLTUND
mdefine_line|#define GEN_FLTUND&t;-5&t;/* fp underflow */
DECL|macro|GEN_FLTINV
mdefine_line|#define GEN_FLTINV&t;-6&t;/* invalid fp operand */
DECL|macro|GEN_FLTINE
mdefine_line|#define GEN_FLTINE&t;-7&t;/* inexact fp operand */
DECL|macro|GEN_DECOVF
mdefine_line|#define GEN_DECOVF&t;-8&t;/* decimal overflow (for COBOL??) */
DECL|macro|GEN_DECDIV
mdefine_line|#define GEN_DECDIV&t;-9&t;/* decimal division by zero */
DECL|macro|GEN_DECINV
mdefine_line|#define GEN_DECINV&t;-10&t;/* invalid decimal operand */
DECL|macro|GEN_ROPRAND
mdefine_line|#define GEN_ROPRAND&t;-11&t;/* reserved operand */
DECL|macro|GEN_ASSERTERR
mdefine_line|#define GEN_ASSERTERR&t;-12&t;/* assertion error */
DECL|macro|GEN_NULPTRERR
mdefine_line|#define GEN_NULPTRERR&t;-13&t;/* null pointer error */
DECL|macro|GEN_STKOVF
mdefine_line|#define GEN_STKOVF&t;-14&t;/* stack overflow */
DECL|macro|GEN_STRLENERR
mdefine_line|#define GEN_STRLENERR&t;-15&t;/* string length error */
DECL|macro|GEN_SUBSTRERR
mdefine_line|#define GEN_SUBSTRERR&t;-16&t;/* substring error */
DECL|macro|GEN_RANGERR
mdefine_line|#define GEN_RANGERR&t;-17&t;/* range error */
DECL|macro|GEN_SUBRNG
mdefine_line|#define GEN_SUBRNG&t;-18
DECL|macro|GEN_SUBRNG1
mdefine_line|#define GEN_SUBRNG1&t;-19&t; 
DECL|macro|GEN_SUBRNG2
mdefine_line|#define GEN_SUBRNG2&t;-20
DECL|macro|GEN_SUBRNG3
mdefine_line|#define GEN_SUBRNG3&t;-21&t;/* these report range errors for */
DECL|macro|GEN_SUBRNG4
mdefine_line|#define GEN_SUBRNG4&t;-22&t;/* subscripting (indexing) at levels 0..7 */
DECL|macro|GEN_SUBRNG5
mdefine_line|#define GEN_SUBRNG5&t;-23
DECL|macro|GEN_SUBRNG6
mdefine_line|#define GEN_SUBRNG6&t;-24
DECL|macro|GEN_SUBRNG7
mdefine_line|#define GEN_SUBRNG7&t;-25
multiline_comment|/* the remaining codes (-26..-1023) are reserved. */
macro_line|#endif /* _ASMAXP_GENTRAP_H */
eof
