multiline_comment|/*&n; *  linux/arch/arm/mach-footbridge/ebsa285-leds.c&n; *&n; *  Copyright (C) 1998-1999 Russell King&n; *&n; * This program is free software; you can redistribute it and/or modify&n; * it under the terms of the GNU General Public License version 2 as&n; * published by the Free Software Foundation.&n; * EBSA-285 control routines.&n; *&n; * The EBSA-285 uses the leds as follows:&n; *  - Green - toggles state every 50 timer interrupts&n; *  - Amber - On if system is not idle&n; *  - Red   - currently unused&n; *&n; * Changelog:&n; *   02-05-1999&t;RMK&t;Various cleanups&n; */
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/module.h&gt;
macro_line|#include &lt;linux/kernel.h&gt;
macro_line|#include &lt;linux/init.h&gt;
macro_line|#include &lt;linux/spinlock.h&gt;
macro_line|#include &lt;asm/hardware.h&gt;
macro_line|#include &lt;asm/leds.h&gt;
macro_line|#include &lt;asm/mach-types.h&gt;
macro_line|#include &lt;asm/system.h&gt;
DECL|macro|LED_STATE_ENABLED
mdefine_line|#define LED_STATE_ENABLED&t;1
DECL|macro|LED_STATE_CLAIMED
mdefine_line|#define LED_STATE_CLAIMED&t;2
DECL|variable|led_state
r_static
r_char
id|led_state
suffix:semicolon
DECL|variable|hw_led_state
r_static
r_char
id|hw_led_state
suffix:semicolon
DECL|variable|leds_lock
r_static
id|spinlock_t
id|leds_lock
op_assign
id|SPIN_LOCK_UNLOCKED
suffix:semicolon
DECL|function|ebsa285_leds_event
r_static
r_void
id|ebsa285_leds_event
c_func
(paren
id|led_event_t
id|evt
)paren
(brace
r_int
r_int
id|flags
suffix:semicolon
id|spin_lock_irqsave
c_func
(paren
op_amp
id|leds_lock
comma
id|flags
)paren
suffix:semicolon
r_switch
c_cond
(paren
id|evt
)paren
(brace
r_case
id|led_start
suffix:colon
id|hw_led_state
op_assign
id|XBUS_LED_RED
op_or
id|XBUS_LED_GREEN
suffix:semicolon
macro_line|#ifndef CONFIG_LEDS_CPU
id|hw_led_state
op_or_assign
id|XBUS_LED_AMBER
suffix:semicolon
macro_line|#endif
id|led_state
op_or_assign
id|LED_STATE_ENABLED
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_stop
suffix:colon
id|led_state
op_and_assign
op_complement
id|LED_STATE_ENABLED
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_claim
suffix:colon
id|led_state
op_or_assign
id|LED_STATE_CLAIMED
suffix:semicolon
id|hw_led_state
op_assign
id|XBUS_LED_RED
op_or
id|XBUS_LED_GREEN
op_or
id|XBUS_LED_AMBER
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_release
suffix:colon
id|led_state
op_and_assign
op_complement
id|LED_STATE_CLAIMED
suffix:semicolon
id|hw_led_state
op_assign
id|XBUS_LED_RED
op_or
id|XBUS_LED_GREEN
op_or
id|XBUS_LED_AMBER
suffix:semicolon
r_break
suffix:semicolon
macro_line|#ifdef CONFIG_LEDS_TIMER
r_case
id|led_timer
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
)paren
id|hw_led_state
op_xor_assign
id|XBUS_LED_GREEN
suffix:semicolon
r_break
suffix:semicolon
macro_line|#endif
macro_line|#ifdef CONFIG_LEDS_CPU
r_case
id|led_idle_start
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
)paren
id|hw_led_state
op_or_assign
id|XBUS_LED_AMBER
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_idle_end
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
)paren
id|hw_led_state
op_and_assign
op_complement
id|XBUS_LED_AMBER
suffix:semicolon
r_break
suffix:semicolon
macro_line|#endif
r_case
id|led_halted
suffix:colon
r_if
c_cond
(paren
op_logical_neg
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
)paren
id|hw_led_state
op_and_assign
op_complement
id|XBUS_LED_RED
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_green_on
suffix:colon
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
id|hw_led_state
op_and_assign
op_complement
id|XBUS_LED_GREEN
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_green_off
suffix:colon
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
id|hw_led_state
op_or_assign
id|XBUS_LED_GREEN
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_amber_on
suffix:colon
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
id|hw_led_state
op_and_assign
op_complement
id|XBUS_LED_AMBER
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_amber_off
suffix:colon
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
id|hw_led_state
op_or_assign
id|XBUS_LED_AMBER
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_red_on
suffix:colon
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
id|hw_led_state
op_and_assign
op_complement
id|XBUS_LED_RED
suffix:semicolon
r_break
suffix:semicolon
r_case
id|led_red_off
suffix:colon
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_CLAIMED
)paren
id|hw_led_state
op_or_assign
id|XBUS_LED_RED
suffix:semicolon
r_break
suffix:semicolon
r_default
suffix:colon
r_break
suffix:semicolon
)brace
r_if
c_cond
(paren
id|led_state
op_amp
id|LED_STATE_ENABLED
)paren
op_star
id|XBUS_LEDS
op_assign
id|hw_led_state
suffix:semicolon
id|spin_unlock_irqrestore
c_func
(paren
op_amp
id|leds_lock
comma
id|flags
)paren
suffix:semicolon
)brace
DECL|function|leds_init
r_static
r_int
id|__init
id|leds_init
c_func
(paren
r_void
)paren
(brace
r_if
c_cond
(paren
id|machine_is_ebsa285
c_func
(paren
)paren
op_logical_or
id|machine_is_co285
c_func
(paren
)paren
)paren
id|leds_event
op_assign
id|ebsa285_leds_event
suffix:semicolon
id|leds_event
c_func
(paren
id|led_start
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
DECL|variable|leds_init
id|__initcall
c_func
(paren
id|leds_init
)paren
suffix:semicolon
eof
