multiline_comment|/*&n; * *** THIS FILE IS AUTOMATICALLY GENERATED.  DO NOT EDIT! ***&n; */
DECL|variable|addr_limit
r_int
r_int
id|addr_limit
op_assign
l_int|56
suffix:semicolon
DECL|macro|__HAS_addr_limit
mdefine_line|#define __HAS_addr_limit
DECL|variable|tss_memmap
r_int
r_int
id|tss_memmap
op_assign
l_int|640
suffix:semicolon
DECL|macro|__HAS_tss_memmap
mdefine_line|#define __HAS_tss_memmap
DECL|variable|mm
r_int
r_int
id|mm
op_assign
l_int|1676
suffix:semicolon
DECL|macro|__HAS_mm
mdefine_line|#define __HAS_mm
DECL|variable|pgd
r_int
r_int
id|pgd
op_assign
l_int|8
suffix:semicolon
DECL|macro|__HAS_pgd
mdefine_line|#define __HAS_pgd
DECL|variable|tss_save
r_int
r_int
id|tss_save
op_assign
l_int|636
suffix:semicolon
DECL|macro|__HAS_tss_save
mdefine_line|#define __HAS_tss_save
DECL|variable|tss_fpesave
r_int
r_int
id|tss_fpesave
op_assign
l_int|492
suffix:semicolon
DECL|macro|__HAS_tss_fpesave
mdefine_line|#define __HAS_tss_fpesave
DECL|variable|tss_memcmap
r_int
r_int
id|tss_memcmap
op_assign
l_int|644
suffix:semicolon
DECL|macro|__HAS_tss_memcmap
mdefine_line|#define __HAS_tss_memcmap
eof
