multiline_comment|/* DO NOT TOUCH, AUTOGENERATED BY OFFSET.C */
macro_line|#ifndef _MIPS_OFFSET_H
DECL|macro|_MIPS_OFFSET_H
mdefine_line|#define _MIPS_OFFSET_H
multiline_comment|/* MIPS pt_regs offsets. */
DECL|macro|PT_R0
mdefine_line|#define PT_R0     0
DECL|macro|PT_R1
mdefine_line|#define PT_R1     8
DECL|macro|PT_R2
mdefine_line|#define PT_R2     16
DECL|macro|PT_R3
mdefine_line|#define PT_R3     24
DECL|macro|PT_R4
mdefine_line|#define PT_R4     32
DECL|macro|PT_R5
mdefine_line|#define PT_R5     40
DECL|macro|PT_R6
mdefine_line|#define PT_R6     48
DECL|macro|PT_R7
mdefine_line|#define PT_R7     56
DECL|macro|PT_R8
mdefine_line|#define PT_R8     64
DECL|macro|PT_R9
mdefine_line|#define PT_R9     72
DECL|macro|PT_R10
mdefine_line|#define PT_R10    80
DECL|macro|PT_R11
mdefine_line|#define PT_R11    88
DECL|macro|PT_R12
mdefine_line|#define PT_R12    96
DECL|macro|PT_R13
mdefine_line|#define PT_R13    104
DECL|macro|PT_R14
mdefine_line|#define PT_R14    112
DECL|macro|PT_R15
mdefine_line|#define PT_R15    120
DECL|macro|PT_R16
mdefine_line|#define PT_R16    128
DECL|macro|PT_R17
mdefine_line|#define PT_R17    136
DECL|macro|PT_R18
mdefine_line|#define PT_R18    144
DECL|macro|PT_R19
mdefine_line|#define PT_R19    152
DECL|macro|PT_R20
mdefine_line|#define PT_R20    160
DECL|macro|PT_R21
mdefine_line|#define PT_R21    168
DECL|macro|PT_R22
mdefine_line|#define PT_R22    176
DECL|macro|PT_R23
mdefine_line|#define PT_R23    184
DECL|macro|PT_R24
mdefine_line|#define PT_R24    192
DECL|macro|PT_R25
mdefine_line|#define PT_R25    200
DECL|macro|PT_R26
mdefine_line|#define PT_R26    208
DECL|macro|PT_R27
mdefine_line|#define PT_R27    216
DECL|macro|PT_R28
mdefine_line|#define PT_R28    224
DECL|macro|PT_R29
mdefine_line|#define PT_R29    232
DECL|macro|PT_R30
mdefine_line|#define PT_R30    240
DECL|macro|PT_R31
mdefine_line|#define PT_R31    248
DECL|macro|PT_LO
mdefine_line|#define PT_LO     256
DECL|macro|PT_HI
mdefine_line|#define PT_HI     264
DECL|macro|PT_EPC
mdefine_line|#define PT_EPC    272
DECL|macro|PT_BVADDR
mdefine_line|#define PT_BVADDR 280
DECL|macro|PT_STATUS
mdefine_line|#define PT_STATUS 288
DECL|macro|PT_CAUSE
mdefine_line|#define PT_CAUSE  296
DECL|macro|PT_SIZE
mdefine_line|#define PT_SIZE   304
multiline_comment|/* MIPS task_struct offsets. */
DECL|macro|TASK_STATE
mdefine_line|#define TASK_STATE         0
DECL|macro|TASK_FLAGS
mdefine_line|#define TASK_FLAGS         8
DECL|macro|TASK_SIGPENDING
mdefine_line|#define TASK_SIGPENDING    16
DECL|macro|TASK_NEED_RESCHED
mdefine_line|#define TASK_NEED_RESCHED  40
DECL|macro|TASK_COUNTER
mdefine_line|#define TASK_COUNTER       56
DECL|macro|TASK_PRIORITY
mdefine_line|#define TASK_PRIORITY      64
DECL|macro|TASK_MM
mdefine_line|#define TASK_MM            80
DECL|macro|TASK_PROCESSOR
mdefine_line|#define TASK_PROCESSOR     100
DECL|macro|TASK_STRUCT_SIZE
mdefine_line|#define TASK_STRUCT_SIZE   1432
multiline_comment|/* MIPS specific thread_struct offsets. */
DECL|macro|THREAD_REG16
mdefine_line|#define THREAD_REG16   896
DECL|macro|THREAD_REG17
mdefine_line|#define THREAD_REG17   904
DECL|macro|THREAD_REG18
mdefine_line|#define THREAD_REG18   912
DECL|macro|THREAD_REG19
mdefine_line|#define THREAD_REG19   920
DECL|macro|THREAD_REG20
mdefine_line|#define THREAD_REG20   928
DECL|macro|THREAD_REG21
mdefine_line|#define THREAD_REG21   936
DECL|macro|THREAD_REG22
mdefine_line|#define THREAD_REG22   944
DECL|macro|THREAD_REG23
mdefine_line|#define THREAD_REG23   952
DECL|macro|THREAD_REG29
mdefine_line|#define THREAD_REG29   960
DECL|macro|THREAD_REG30
mdefine_line|#define THREAD_REG30   968
DECL|macro|THREAD_REG31
mdefine_line|#define THREAD_REG31   976
DECL|macro|THREAD_STATUS
mdefine_line|#define THREAD_STATUS  984
DECL|macro|THREAD_FPU
mdefine_line|#define THREAD_FPU     992
DECL|macro|THREAD_BVADDR
mdefine_line|#define THREAD_BVADDR  1256
DECL|macro|THREAD_BUADDR
mdefine_line|#define THREAD_BUADDR  1264
DECL|macro|THREAD_ECODE
mdefine_line|#define THREAD_ECODE   1272
DECL|macro|THREAD_TRAPNO
mdefine_line|#define THREAD_TRAPNO  1280
DECL|macro|THREAD_MFLAGS
mdefine_line|#define THREAD_MFLAGS  1288
DECL|macro|THREAD_CURDS
mdefine_line|#define THREAD_CURDS   1296
DECL|macro|THREAD_TRAMP
mdefine_line|#define THREAD_TRAMP   1304
DECL|macro|THREAD_OLDCTX
mdefine_line|#define THREAD_OLDCTX  1312
multiline_comment|/* Linux mm_struct offsets. */
DECL|macro|MM_USERS
mdefine_line|#define MM_USERS      32
DECL|macro|MM_PGD
mdefine_line|#define MM_PGD        24
DECL|macro|MM_CONTEXT
mdefine_line|#define MM_CONTEXT    112
multiline_comment|/* Linux sigcontext offsets. */
DECL|macro|SC_REGS
mdefine_line|#define SC_REGS       0
DECL|macro|SC_FPREGS
mdefine_line|#define SC_FPREGS     256
DECL|macro|SC_MDHI
mdefine_line|#define SC_MDHI       512
DECL|macro|SC_MDLO
mdefine_line|#define SC_MDLO       520
DECL|macro|SC_PC
mdefine_line|#define SC_PC         528
DECL|macro|SC_STATUS
mdefine_line|#define SC_STATUS     536
DECL|macro|SC_OWNEDFP
mdefine_line|#define SC_OWNEDFP    540
DECL|macro|SC_FPC_CSR
mdefine_line|#define SC_FPC_CSR    544
DECL|macro|SC_FPC_EIR
mdefine_line|#define SC_FPC_EIR    548
DECL|macro|SC_CAUSE
mdefine_line|#define SC_CAUSE      552
DECL|macro|SC_BADVADDR
mdefine_line|#define SC_BADVADDR   556
macro_line|#endif /* !(_MIPS_OFFSET_H) */
eof
