multiline_comment|/*&n; * linux/fs/fat/fatfs_syms.c&n; *&n; * Exported kernel symbols for the low-level FAT-based fs support.&n; *&n; */
DECL|macro|ASC_LINUX_VERSION
mdefine_line|#define ASC_LINUX_VERSION(V, P, S)&t;(((V) * 65536) + ((P) * 256) + (S))
macro_line|#include &lt;linux/version.h&gt;
macro_line|#include &lt;linux/module.h&gt;
macro_line|#include &lt;linux/mm.h&gt;
macro_line|#include &lt;linux/msdos_fs.h&gt;
macro_line|#include &lt;linux/fat_cvf.h&gt;
macro_line|#include &quot;msbuffer.h&quot;
macro_line|#include &quot;tables.h&quot;
r_extern
r_struct
id|file_operations
id|fat_dir_operations
suffix:semicolon
DECL|variable|fat_add_cluster
id|EXPORT_SYMBOL
c_func
(paren
id|fat_add_cluster
)paren
suffix:semicolon
DECL|variable|fat_bmap
id|EXPORT_SYMBOL
c_func
(paren
id|fat_bmap
)paren
suffix:semicolon
DECL|variable|fat_brelse
id|EXPORT_SYMBOL
c_func
(paren
id|fat_brelse
)paren
suffix:semicolon
DECL|variable|fat_cache_inval_inode
id|EXPORT_SYMBOL
c_func
(paren
id|fat_cache_inval_inode
)paren
suffix:semicolon
DECL|variable|fat_date_unix2dos
id|EXPORT_SYMBOL
c_func
(paren
id|fat_date_unix2dos
)paren
suffix:semicolon
DECL|variable|fat_delete_inode
id|EXPORT_SYMBOL
c_func
(paren
id|fat_delete_inode
)paren
suffix:semicolon
DECL|variable|fat_dir_operations
id|EXPORT_SYMBOL
c_func
(paren
id|fat_dir_operations
)paren
suffix:semicolon
DECL|variable|fat_esc2uni
id|EXPORT_SYMBOL
c_func
(paren
id|fat_esc2uni
)paren
suffix:semicolon
DECL|variable|fat_file_read
id|EXPORT_SYMBOL
c_func
(paren
id|fat_file_read
)paren
suffix:semicolon
DECL|variable|fat_file_write
id|EXPORT_SYMBOL
c_func
(paren
id|fat_file_write
)paren
suffix:semicolon
DECL|variable|fat_fs_panic
id|EXPORT_SYMBOL
c_func
(paren
id|fat_fs_panic
)paren
suffix:semicolon
DECL|variable|fat_get_entry
id|EXPORT_SYMBOL
c_func
(paren
id|fat_get_entry
)paren
suffix:semicolon
DECL|variable|fat_lock_creation
id|EXPORT_SYMBOL
c_func
(paren
id|fat_lock_creation
)paren
suffix:semicolon
DECL|variable|fat_mark_buffer_dirty
id|EXPORT_SYMBOL
c_func
(paren
id|fat_mark_buffer_dirty
)paren
suffix:semicolon
DECL|variable|fat_mmap
id|EXPORT_SYMBOL
c_func
(paren
id|fat_mmap
)paren
suffix:semicolon
DECL|variable|fat_notify_change
id|EXPORT_SYMBOL
c_func
(paren
id|fat_notify_change
)paren
suffix:semicolon
DECL|variable|fat_parent_ino
id|EXPORT_SYMBOL
c_func
(paren
id|fat_parent_ino
)paren
suffix:semicolon
DECL|variable|fat_put_inode
id|EXPORT_SYMBOL
c_func
(paren
id|fat_put_inode
)paren
suffix:semicolon
DECL|variable|fat_put_super
id|EXPORT_SYMBOL
c_func
(paren
id|fat_put_super
)paren
suffix:semicolon
DECL|variable|fat_read_inode
id|EXPORT_SYMBOL
c_func
(paren
id|fat_read_inode
)paren
suffix:semicolon
DECL|variable|fat_read_super
id|EXPORT_SYMBOL
c_func
(paren
id|fat_read_super
)paren
suffix:semicolon
DECL|variable|fat_readdirx
id|EXPORT_SYMBOL
c_func
(paren
id|fat_readdirx
)paren
suffix:semicolon
DECL|variable|fat_readdir
id|EXPORT_SYMBOL
c_func
(paren
id|fat_readdir
)paren
suffix:semicolon
DECL|variable|fat_scan
id|EXPORT_SYMBOL
c_func
(paren
id|fat_scan
)paren
suffix:semicolon
DECL|variable|fat_smap
id|EXPORT_SYMBOL
c_func
(paren
id|fat_smap
)paren
suffix:semicolon
DECL|variable|fat_statfs
id|EXPORT_SYMBOL
c_func
(paren
id|fat_statfs
)paren
suffix:semicolon
DECL|variable|fat_truncate
id|EXPORT_SYMBOL
c_func
(paren
id|fat_truncate
)paren
suffix:semicolon
DECL|variable|fat_uni2esc
id|EXPORT_SYMBOL
c_func
(paren
id|fat_uni2esc
)paren
suffix:semicolon
DECL|variable|fat_unlock_creation
id|EXPORT_SYMBOL
c_func
(paren
id|fat_unlock_creation
)paren
suffix:semicolon
DECL|variable|fat_write_inode
id|EXPORT_SYMBOL
c_func
(paren
id|fat_write_inode
)paren
suffix:semicolon
DECL|variable|register_cvf_format
id|EXPORT_SYMBOL
c_func
(paren
id|register_cvf_format
)paren
suffix:semicolon
DECL|variable|unregister_cvf_format
id|EXPORT_SYMBOL
c_func
(paren
id|unregister_cvf_format
)paren
suffix:semicolon
DECL|variable|fat_get_cluster
id|EXPORT_SYMBOL
c_func
(paren
id|fat_get_cluster
)paren
suffix:semicolon
DECL|variable|lock_fat
id|EXPORT_SYMBOL
c_func
(paren
id|lock_fat
)paren
suffix:semicolon
DECL|variable|unlock_fat
id|EXPORT_SYMBOL
c_func
(paren
id|unlock_fat
)paren
suffix:semicolon
DECL|function|init_fat_fs
r_int
id|init_fat_fs
c_func
(paren
r_void
)paren
(brace
r_return
l_int|0
suffix:semicolon
)brace
eof
