multiline_comment|/******************************************************************************&n; *&n; * Name: acinterp.h - Interpreter subcomponent prototypes and defines&n; *       $Revision: 86 $&n; *&n; *****************************************************************************/
multiline_comment|/*&n; *  Copyright (C) 2000 R. Byron Moore&n; *&n; *  This program is free software; you can redistribute it and/or modify&n; *  it under the terms of the GNU General Public License as published by&n; *  the Free Software Foundation; either version 2 of the License, or&n; *  (at your option) any later version.&n; *&n; *  This program is distributed in the hope that it will be useful,&n; *  but WITHOUT ANY WARRANTY; without even the implied warranty of&n; *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the&n; *  GNU General Public License for more details.&n; *&n; *  You should have received a copy of the GNU General Public License&n; *  along with this program; if not, write to the Free Software&n; *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA&n; */
macro_line|#ifndef __ACINTERP_H__
DECL|macro|__ACINTERP_H__
mdefine_line|#define __ACINTERP_H__
DECL|macro|WALK_OPERANDS
mdefine_line|#define WALK_OPERANDS       &amp;(walk_state-&gt;operands [walk_state-&gt;num_operands -1])
multiline_comment|/* Interpreter constants */
DECL|macro|AML_END_OF_BLOCK
mdefine_line|#define AML_END_OF_BLOCK            -1
DECL|macro|PUSH_PKG_LENGTH
mdefine_line|#define PUSH_PKG_LENGTH             1
DECL|macro|DO_NOT_PUSH_PKG_LENGTH
mdefine_line|#define DO_NOT_PUSH_PKG_LENGTH      0
DECL|macro|STACK_TOP
mdefine_line|#define STACK_TOP                   0
DECL|macro|STACK_BOTTOM
mdefine_line|#define STACK_BOTTOM                (u32) -1
multiline_comment|/* Constants for global &quot;When_to_parse_methods&quot; */
DECL|macro|METHOD_PARSE_AT_INIT
mdefine_line|#define METHOD_PARSE_AT_INIT        0x0
DECL|macro|METHOD_PARSE_JUST_IN_TIME
mdefine_line|#define METHOD_PARSE_JUST_IN_TIME   0x1
DECL|macro|METHOD_DELETE_AT_COMPLETION
mdefine_line|#define METHOD_DELETE_AT_COMPLETION 0x2
id|ACPI_STATUS
id|acpi_aml_resolve_operands
(paren
id|u16
id|opcode
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|stack_ptr
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
multiline_comment|/*&n; * amxface - External interpreter interfaces&n; */
id|ACPI_STATUS
id|acpi_aml_load_table
(paren
id|ACPI_TABLE_TYPE
id|table_id
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_execute_method
(paren
id|ACPI_NAMESPACE_NODE
op_star
id|method_node
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|params
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_obj_desc
)paren
suffix:semicolon
multiline_comment|/*&n; * amfield - ACPI AML (p-code) execution - field manipulation&n; */
id|ACPI_STATUS
id|acpi_aml_read_field
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
comma
r_void
op_star
id|buffer
comma
id|u32
id|buffer_length
comma
id|u32
id|byte_length
comma
id|u32
id|datum_length
comma
id|u32
id|bit_granularity
comma
id|u32
id|byte_granularity
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_write_field
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
comma
r_void
op_star
id|buffer
comma
id|u32
id|buffer_length
comma
id|u32
id|byte_length
comma
id|u32
id|datum_length
comma
id|u32
id|bit_granularity
comma
id|u32
id|byte_granularity
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_setup_field
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
comma
id|ACPI_OPERAND_OBJECT
op_star
id|rgn_desc
comma
id|u32
id|field_bit_width
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_read_field_data
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
comma
id|u32
id|field_byte_offset
comma
id|u32
id|field_bit_width
comma
id|u32
op_star
id|value
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_access_named_field
(paren
id|u32
id|mode
comma
id|ACPI_HANDLE
id|named_field
comma
r_void
op_star
id|buffer
comma
id|u32
id|length
)paren
suffix:semicolon
multiline_comment|/*&n; * ammisc - ACPI AML (p-code) execution - specific opcodes&n; */
id|ACPI_STATUS
id|acpi_aml_exec_create_field
(paren
id|u8
op_star
id|aml_ptr
comma
id|u32
id|aml_length
comma
id|ACPI_NAMESPACE_NODE
op_star
id|node
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_reconfiguration
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_fatal
(paren
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_index
(paren
id|ACPI_WALK_STATE
op_star
id|walk_state
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_match
(paren
id|ACPI_WALK_STATE
op_star
id|walk_state
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_create_mutex
(paren
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_create_processor
(paren
id|ACPI_PARSE_OBJECT
op_star
id|op
comma
id|ACPI_HANDLE
id|processor_nTE
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_create_power_resource
(paren
id|ACPI_PARSE_OBJECT
op_star
id|op
comma
id|ACPI_HANDLE
id|processor_nTE
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_create_region
(paren
id|u8
op_star
id|aml_ptr
comma
id|u32
id|acpi_aml_length
comma
id|u8
id|region_space
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_create_event
(paren
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_create_alias
(paren
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_create_method
(paren
id|u8
op_star
id|aml_ptr
comma
id|u32
id|acpi_aml_length
comma
id|u32
id|method_flags
comma
id|ACPI_HANDLE
id|method
)paren
suffix:semicolon
multiline_comment|/*&n; * amprep - ACPI AML (p-code) execution - prep utilities&n; */
id|ACPI_STATUS
id|acpi_aml_prep_def_field_value
(paren
id|ACPI_NAMESPACE_NODE
op_star
id|node
comma
id|ACPI_HANDLE
id|region
comma
id|u8
id|field_flags
comma
id|u8
id|field_attribute
comma
id|u32
id|field_position
comma
id|u32
id|field_length
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_prep_bank_field_value
(paren
id|ACPI_NAMESPACE_NODE
op_star
id|node
comma
id|ACPI_HANDLE
id|region
comma
id|ACPI_HANDLE
id|bank_reg
comma
id|u32
id|bank_val
comma
id|u8
id|field_flags
comma
id|u8
id|field_attribute
comma
id|u32
id|field_position
comma
id|u32
id|field_length
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_prep_index_field_value
(paren
id|ACPI_NAMESPACE_NODE
op_star
id|node
comma
id|ACPI_HANDLE
id|index_reg
comma
id|ACPI_HANDLE
id|data_reg
comma
id|u8
id|field_flags
comma
id|u8
id|field_attribute
comma
id|u32
id|field_position
comma
id|u32
id|field_length
)paren
suffix:semicolon
multiline_comment|/*&n; * amsystem - Interface to OS services&n; */
id|u16
id|acpi_aml_system_thread_id
(paren
r_void
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_do_notify_op
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|value
comma
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
)paren
suffix:semicolon
r_void
id|acpi_aml_system_do_suspend
c_func
(paren
id|u32
id|time
)paren
suffix:semicolon
r_void
id|acpi_aml_system_do_stall
(paren
id|u32
id|time
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_acquire_mutex
c_func
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|time
comma
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_release_mutex
c_func
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_signal_event
c_func
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_wait_event
c_func
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|time
comma
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_reset_event
c_func
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_wait_semaphore
(paren
id|ACPI_HANDLE
id|semaphore
comma
id|u32
id|timeout
)paren
suffix:semicolon
multiline_comment|/*&n; * ammonadic - ACPI AML (p-code) execution, monadic operators&n; */
id|ACPI_STATUS
id|acpi_aml_exec_monadic1
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_monadic2
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_monadic2_r
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_desc
)paren
suffix:semicolon
multiline_comment|/*&n; * amdyadic - ACPI AML (p-code) execution, dyadic operators&n; */
id|ACPI_STATUS
id|acpi_aml_exec_dyadic1
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_dyadic2
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_dyadic2_r
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_desc
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_dyadic2_s
(paren
id|u16
id|opcode
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
comma
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|return_desc
)paren
suffix:semicolon
multiline_comment|/*&n; * amresolv  - Object resolution and get value functions&n; */
id|ACPI_STATUS
id|acpi_aml_resolve_to_value
(paren
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|stack_ptr
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_resolve_node_to_value
(paren
id|ACPI_NAMESPACE_NODE
op_star
op_star
id|stack_ptr
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_resolve_object_to_value
(paren
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|stack_ptr
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_get_field_unit_value
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|field_desc
comma
id|ACPI_OPERAND_OBJECT
op_star
id|result_desc
)paren
suffix:semicolon
multiline_comment|/*&n; * amdump - Scanner debug output routines&n; */
r_void
id|acpi_aml_show_hex_value
(paren
id|u32
id|byte_count
comma
id|u8
op_star
id|aml_ptr
comma
id|u32
id|lead_space
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_dump_operand
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|entry_desc
)paren
suffix:semicolon
r_void
id|acpi_aml_dump_operands
(paren
id|ACPI_OPERAND_OBJECT
op_star
op_star
id|operands
comma
id|OPERATING_MODE
id|interpreter_mode
comma
id|NATIVE_CHAR
op_star
id|ident
comma
id|u32
id|num_levels
comma
id|NATIVE_CHAR
op_star
id|note
comma
id|NATIVE_CHAR
op_star
id|module_name
comma
id|u32
id|line_number
)paren
suffix:semicolon
r_void
id|acpi_aml_dump_object_descriptor
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|object
comma
id|u32
id|flags
)paren
suffix:semicolon
r_void
id|acpi_aml_dump_node
(paren
id|ACPI_NAMESPACE_NODE
op_star
id|node
comma
id|u32
id|flags
)paren
suffix:semicolon
multiline_comment|/*&n; * amnames - interpreter/scanner name load/execute&n; */
id|NATIVE_CHAR
op_star
id|acpi_aml_allocate_name_string
(paren
id|u32
id|prefix_count
comma
id|u32
id|num_name_segs
)paren
suffix:semicolon
id|u32
id|acpi_aml_good_char
(paren
id|u32
id|character
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_exec_name_segment
(paren
id|u8
op_star
op_star
id|in_aml_address
comma
id|NATIVE_CHAR
op_star
id|name_string
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_get_name_string
(paren
id|OBJECT_TYPE_INTERNAL
id|data_type
comma
id|u8
op_star
id|in_aml_address
comma
id|NATIVE_CHAR
op_star
op_star
id|out_name_string
comma
id|u32
op_star
id|out_name_length
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_do_name
(paren
id|ACPI_OBJECT_TYPE
id|data_type
comma
id|OPERATING_MODE
id|load_exec_mode
)paren
suffix:semicolon
multiline_comment|/*&n; * amstore - Object store support&n; */
id|ACPI_STATUS
id|acpi_aml_exec_store
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|val_desc
comma
id|ACPI_OPERAND_OBJECT
op_star
id|dest_desc
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_store_object_to_object
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|val_desc
comma
id|ACPI_OPERAND_OBJECT
op_star
id|dest_desc
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_store_object_to_node
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|val_desc
comma
id|ACPI_NAMESPACE_NODE
op_star
id|node
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
multiline_comment|/*&n; * amutils - interpreter/scanner utilities&n; */
r_void
id|acpi_aml_enter_interpreter
(paren
r_void
)paren
suffix:semicolon
r_void
id|acpi_aml_exit_interpreter
(paren
r_void
)paren
suffix:semicolon
r_void
id|acpi_aml_truncate_for32bit_table
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|obj_desc
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
id|u8
id|acpi_aml_validate_object_type
(paren
id|ACPI_OBJECT_TYPE
id|type
)paren
suffix:semicolon
id|u8
id|acpi_aml_acquire_global_lock
(paren
id|u32
id|rule
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_release_global_lock
(paren
id|u8
id|locked
)paren
suffix:semicolon
id|u32
id|acpi_aml_digits_needed
(paren
id|ACPI_INTEGER
id|value
comma
id|u32
id|base
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_eisa_id_to_string
(paren
id|u32
id|numeric_id
comma
id|NATIVE_CHAR
op_star
id|out_string
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_unsigned_integer_to_string
(paren
id|ACPI_INTEGER
id|value
comma
id|NATIVE_CHAR
op_star
id|out_string
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_build_copy_internal_package_object
(paren
id|ACPI_OPERAND_OBJECT
op_star
id|source_obj
comma
id|ACPI_OPERAND_OBJECT
op_star
id|dest_obj
comma
id|ACPI_WALK_STATE
op_star
id|walk_state
)paren
suffix:semicolon
multiline_comment|/*&n; * amregion - default Op_region handlers&n; */
id|ACPI_STATUS
id|acpi_aml_system_memory_space_handler
(paren
id|u32
id|function
comma
id|ACPI_PHYSICAL_ADDRESS
id|address
comma
id|u32
id|bit_width
comma
id|u32
op_star
id|value
comma
r_void
op_star
id|handler_context
comma
r_void
op_star
id|region_context
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_system_io_space_handler
(paren
id|u32
id|function
comma
id|ACPI_PHYSICAL_ADDRESS
id|address
comma
id|u32
id|bit_width
comma
id|u32
op_star
id|value
comma
r_void
op_star
id|handler_context
comma
r_void
op_star
id|region_context
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_pci_config_space_handler
(paren
id|u32
id|function
comma
id|ACPI_PHYSICAL_ADDRESS
id|address
comma
id|u32
id|bit_width
comma
id|u32
op_star
id|value
comma
r_void
op_star
id|handler_context
comma
r_void
op_star
id|region_context
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_embedded_controller_space_handler
(paren
id|u32
id|function
comma
id|ACPI_PHYSICAL_ADDRESS
id|address
comma
id|u32
id|bit_width
comma
id|u32
op_star
id|value
comma
r_void
op_star
id|handler_context
comma
r_void
op_star
id|region_context
)paren
suffix:semicolon
id|ACPI_STATUS
id|acpi_aml_sm_bus_space_handler
(paren
id|u32
id|function
comma
id|ACPI_PHYSICAL_ADDRESS
id|address
comma
id|u32
id|bit_width
comma
id|u32
op_star
id|value
comma
r_void
op_star
id|handler_context
comma
r_void
op_star
id|region_context
)paren
suffix:semicolon
macro_line|#endif /* __INTERP_H__ */
eof
