multiline_comment|/*&n; *&t;Precise Delay Loops for i386&n; *&n; *&t;Copyright (C) 1993 Linus Torvalds&n; *&t;Copyright (C) 1997 Martin Mares &lt;mj@atrey.karlin.mff.cuni.cz&gt;&n; *&n; *&t;The __delay function must _NOT_ be inlined as its execution time&n; *&t;depends wildly on alignment on many x86 processors. The additional&n; *&t;jump magic is needed to get the timing stable on all the CPU&squot;s&n; *&t;we have to worry about.&n; */
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/sched.h&gt;
macro_line|#include &lt;linux/delay.h&gt;
macro_line|#include &lt;asm/delay.h&gt;
macro_line|#ifdef CONFIG_SMP
macro_line|#include &lt;asm/smp.h&gt;
macro_line|#endif
DECL|variable|x86_udelay_tsc
r_int
id|x86_udelay_tsc
op_assign
l_int|0
suffix:semicolon
multiline_comment|/* Delay via TSC */
multiline_comment|/*&n; *&t;Do a udelay using the TSC for any CPU that happens&n; *&t;to have one that we trust.&n; */
DECL|function|__rdtsc_delay
r_static
r_void
id|__rdtsc_delay
c_func
(paren
r_int
r_int
id|loops
)paren
(brace
r_int
r_int
id|bclock
comma
id|now
suffix:semicolon
id|rdtscl
c_func
(paren
id|bclock
)paren
suffix:semicolon
r_do
(brace
id|rdtscl
c_func
(paren
id|now
)paren
suffix:semicolon
)brace
r_while
c_loop
(paren
(paren
id|now
op_minus
id|bclock
)paren
OL
id|loops
)paren
(brace
suffix:semicolon
)brace
)brace
multiline_comment|/*&n; *&t;Non TSC based delay loop for 386, 486, MediaGX&n; */
DECL|function|__loop_delay
r_static
r_void
id|__loop_delay
c_func
(paren
r_int
r_int
id|loops
)paren
(brace
r_int
id|d0
suffix:semicolon
id|__asm__
id|__volatile__
c_func
(paren
l_string|&quot;&bslash;tjmp 1f&bslash;n&quot;
l_string|&quot;.align 16&bslash;n&quot;
l_string|&quot;1:&bslash;tjmp 2f&bslash;n&quot;
l_string|&quot;.align 16&bslash;n&quot;
l_string|&quot;2:&bslash;tdecl %0&bslash;n&bslash;tjns 2b&quot;
suffix:colon
l_string|&quot;=&amp;a&quot;
(paren
id|d0
)paren
suffix:colon
l_string|&quot;0&quot;
(paren
id|loops
)paren
)paren
suffix:semicolon
)brace
DECL|function|__delay
r_void
id|__delay
c_func
(paren
r_int
r_int
id|loops
)paren
(brace
r_if
c_cond
(paren
id|x86_udelay_tsc
)paren
(brace
id|__rdtsc_delay
c_func
(paren
id|loops
)paren
suffix:semicolon
)brace
r_else
id|__loop_delay
c_func
(paren
id|loops
)paren
suffix:semicolon
)brace
DECL|function|__const_udelay
r_inline
r_void
id|__const_udelay
c_func
(paren
r_int
r_int
id|xloops
)paren
(brace
r_int
id|d0
suffix:semicolon
id|__asm__
c_func
(paren
l_string|&quot;mull %0&quot;
suffix:colon
l_string|&quot;=d&quot;
(paren
id|xloops
)paren
comma
l_string|&quot;=&amp;a&quot;
(paren
id|d0
)paren
suffix:colon
l_string|&quot;1&quot;
(paren
id|xloops
)paren
comma
l_string|&quot;0&quot;
(paren
id|current_cpu_data.loops_per_jiffy
)paren
)paren
suffix:semicolon
id|__delay
c_func
(paren
id|xloops
op_star
id|HZ
)paren
suffix:semicolon
)brace
DECL|function|__udelay
r_void
id|__udelay
c_func
(paren
r_int
r_int
id|usecs
)paren
(brace
id|__const_udelay
c_func
(paren
id|usecs
op_star
l_int|0x000010c6
)paren
suffix:semicolon
multiline_comment|/* 2**32 / 1000000 */
)brace
eof
