multiline_comment|/*&n; * Setup pointers to hardware dependand routines.&n; *&n; * This file is subject to the terms and conditions of the GNU General Public&n; * License.  See the file &quot;COPYING&quot; in the main directory of this archive&n; * for more details.&n; *&n; * Copyright (C) 1996, 1997 by Ralf Baechle&n; */
macro_line|#include &lt;linux/bios32.h&gt;
macro_line|#include &lt;linux/config.h&gt;
macro_line|#include &lt;linux/ioport.h&gt;
macro_line|#include &lt;linux/sched.h&gt;
macro_line|#include &lt;linux/interrupt.h&gt;
macro_line|#include &lt;linux/pci.h&gt;
macro_line|#include &lt;linux/timex.h&gt;
macro_line|#include &lt;asm/bootinfo.h&gt;
macro_line|#include &lt;asm/io.h&gt;
macro_line|#include &lt;asm/irq.h&gt;
macro_line|#include &lt;asm/cobalt.h&gt;
macro_line|#include &lt;asm/pci.h&gt;
macro_line|#include &lt;asm/processor.h&gt;
macro_line|#include &lt;asm/ptrace.h&gt;
macro_line|#include &lt;asm/reboot.h&gt;
macro_line|#include &lt;asm/vector.h&gt;
r_extern
r_void
id|cobalt_machine_restart
c_func
(paren
r_char
op_star
id|command
)paren
suffix:semicolon
r_extern
r_void
id|cobalt_machine_halt
c_func
(paren
r_void
)paren
suffix:semicolon
r_extern
r_void
id|cobalt_machine_power_off
c_func
(paren
r_void
)paren
suffix:semicolon
r_extern
r_int
id|serial_console
suffix:semicolon
multiline_comment|/*&n; * Initial irq handlers.&n; */
DECL|function|no_action
r_static
r_void
id|no_action
c_func
(paren
r_int
id|cpl
comma
r_void
op_star
id|dev_id
comma
r_struct
id|pt_regs
op_star
id|regs
)paren
(brace
)brace
multiline_comment|/*&n; * IRQ2 is cascade interrupt to second interrupt controller&n; */
DECL|variable|irq2
r_static
r_struct
id|irqaction
id|irq2
op_assign
(brace
id|no_action
comma
l_int|0
comma
l_int|0
comma
l_string|&quot;cascade&quot;
comma
l_int|NULL
comma
l_int|NULL
)brace
suffix:semicolon
r_extern
r_struct
id|feature
id|cobalt_feature
suffix:semicolon
r_extern
id|asmlinkage
r_void
id|cobalt_handle_int
c_func
(paren
r_void
)paren
suffix:semicolon
DECL|function|cobalt_irq_setup
r_static
r_void
id|cobalt_irq_setup
c_func
(paren
r_void
)paren
(brace
multiline_comment|/*&n;&t; * Clear all of the interrupts while we change the able around a bit.&n;&t; */
id|set_cp0_status
c_func
(paren
id|ST0_IM
comma
l_int|0
)paren
suffix:semicolon
multiline_comment|/* Sets the exception_handler array. */
id|set_except_vector
c_func
(paren
l_int|0
comma
id|cobalt_handle_int
)paren
suffix:semicolon
id|request_region
c_func
(paren
l_int|0xb0000020
comma
l_int|0x20
comma
l_string|&quot;pic1&quot;
)paren
suffix:semicolon
id|request_region
c_func
(paren
l_int|0xb00000A0
comma
l_int|0x20
comma
l_string|&quot;pic2&quot;
)paren
suffix:semicolon
id|setup_x86_irq
c_func
(paren
l_int|2
comma
op_amp
id|irq2
)paren
suffix:semicolon
id|cli
c_func
(paren
)paren
suffix:semicolon
id|set_cp0_status
c_func
(paren
id|ST0_IM
comma
id|IE_IRQ4
op_or
id|IE_IRQ3
op_or
id|IE_IRQ2
op_or
id|IE_IRQ1
op_or
id|IE_IRQ0
)paren
suffix:semicolon
multiline_comment|/* Setup VIA irq mask */
id|VIA_PORT_WRITE
c_func
(paren
l_int|0x20
comma
l_int|0x10
)paren
suffix:semicolon
id|VIA_PORT_WRITE
c_func
(paren
l_int|0x21
comma
l_int|0x00
)paren
suffix:semicolon
id|VIA_PORT_WRITE
c_func
(paren
l_int|0x21
comma
l_int|0x00
)paren
suffix:semicolon
id|VIA_PORT_WRITE
c_func
(paren
l_int|0xa0
comma
l_int|0x10
)paren
suffix:semicolon
id|VIA_PORT_WRITE
c_func
(paren
l_int|0xa1
comma
l_int|0x00
)paren
suffix:semicolon
id|VIA_PORT_WRITE
c_func
(paren
l_int|0xa1
comma
l_int|0x00
)paren
suffix:semicolon
)brace
DECL|variable|board_time_init
r_void
(paren
op_star
id|board_time_init
)paren
(paren
r_struct
id|irqaction
op_star
id|irq
)paren
suffix:semicolon
DECL|function|cobalt_calibrate_timer
r_static
r_void
id|cobalt_calibrate_timer
c_func
(paren
r_void
)paren
(brace
r_volatile
r_int
r_int
op_star
id|timer_reg
op_assign
(paren
r_volatile
r_int
r_int
op_star
)paren
l_int|0xb4000850
suffix:semicolon
multiline_comment|/* Default to 150MHZ, since this is what we are shipping. */
op_star
id|timer_reg
op_assign
l_int|500000
suffix:semicolon
)brace
DECL|function|cobalt_time_init
r_static
r_void
id|cobalt_time_init
c_func
(paren
r_struct
id|irqaction
op_star
id|irq
)paren
(brace
multiline_comment|/* Load timer value for 100 Hz */
id|cobalt_calibrate_timer
c_func
(paren
)paren
suffix:semicolon
multiline_comment|/* *((volatile unsigned long *) 0xb4000850) = (unsigned long) 440000; */
id|setup_x86_irq
c_func
(paren
l_int|0
comma
id|irq
)paren
suffix:semicolon
multiline_comment|/* Enable timer ints */
op_star
(paren
(paren
r_volatile
r_int
r_int
op_star
)paren
l_int|0xb4000864
)paren
op_assign
(paren
r_int
r_int
)paren
l_int|0x00000003
suffix:semicolon
multiline_comment|/* Unmask timer int */
op_star
(paren
(paren
r_volatile
r_int
r_int
op_star
)paren
l_int|0xb4000c1c
)paren
op_assign
(paren
r_int
r_int
)paren
l_int|0x00000100
suffix:semicolon
)brace
r_extern
r_struct
id|pci_ops
id|qube_pci_ops
suffix:semicolon
DECL|variable|cobalt_serial_present
r_int
id|cobalt_serial_present
suffix:semicolon
DECL|variable|cobalt_serial_type
r_int
id|cobalt_serial_type
suffix:semicolon
DECL|variable|cobalt_is_raq
r_int
id|cobalt_is_raq
suffix:semicolon
DECL|function|cobalt_setup
r_void
id|cobalt_setup
c_func
(paren
r_void
)paren
(brace
id|tag
op_star
id|atag
suffix:semicolon
multiline_comment|/*&n;&t; * We just check if a tag_screen_info can be gathered&n;&t; * in setup_arch(), if yes we don&squot;t proceed futher...&n;&t; */
id|atag
op_assign
id|bi_TagFind
c_func
(paren
id|tag_screen_info
)paren
suffix:semicolon
r_if
c_cond
(paren
op_logical_neg
id|atag
)paren
(brace
multiline_comment|/*&n;&t;&t; * If no, we try to find the tag_arc_displayinfo which is&n;&t;&t; * always created by Milo for an ARC box (for now Milo only&n;&t;&t; * works on ARC boxes :) -Stoned.&n;&t;&t; */
id|atag
op_assign
id|bi_TagFind
c_func
(paren
id|tag_arcdisplayinfo
)paren
suffix:semicolon
r_if
c_cond
(paren
id|atag
)paren
(brace
id|screen_info.orig_x
op_assign
(paren
(paren
id|mips_arc_DisplayInfo
op_star
)paren
id|TAGVALPTR
c_func
(paren
id|atag
)paren
)paren
op_member_access_from_pointer
id|cursor_x
suffix:semicolon
id|screen_info.orig_y
op_assign
(paren
(paren
id|mips_arc_DisplayInfo
op_star
)paren
id|TAGVALPTR
c_func
(paren
id|atag
)paren
)paren
op_member_access_from_pointer
id|cursor_y
suffix:semicolon
id|screen_info.orig_video_cols
op_assign
(paren
(paren
id|mips_arc_DisplayInfo
op_star
)paren
id|TAGVALPTR
c_func
(paren
id|atag
)paren
)paren
op_member_access_from_pointer
id|columns
suffix:semicolon
id|screen_info.orig_video_lines
op_assign
(paren
(paren
id|mips_arc_DisplayInfo
op_star
)paren
id|TAGVALPTR
c_func
(paren
id|atag
)paren
)paren
op_member_access_from_pointer
id|lines
suffix:semicolon
)brace
)brace
id|_machine_restart
op_assign
id|cobalt_machine_restart
suffix:semicolon
id|_machine_halt
op_assign
id|cobalt_machine_halt
suffix:semicolon
id|_machine_power_off
op_assign
id|cobalt_machine_power_off
suffix:semicolon
id|irq_setup
op_assign
id|cobalt_irq_setup
suffix:semicolon
id|board_time_init
op_assign
id|cobalt_time_init
suffix:semicolon
id|feature
op_assign
op_amp
id|cobalt_feature
suffix:semicolon
id|mips_io_port_base
op_assign
id|COBALT_LOCAL_IO_SPACE
suffix:semicolon
id|pci_ops
op_assign
op_amp
id|qube_pci_ops
suffix:semicolon
macro_line|#ifdef CONFIG_COBALT_SERIAL
id|serial_console
op_assign
l_int|1
suffix:semicolon
macro_line|#endif /* CONFIG_COBALT_SERIAL */
multiline_comment|/* We have to do this early, here, before the value could&n;&t; * possibly be overwritten by the bootup sequence.&n;&t; */
id|cobalt_serial_present
op_assign
op_star
(paren
(paren
r_int
r_int
op_star
)paren
l_int|0xa020001c
)paren
suffix:semicolon
id|cobalt_serial_type
op_assign
op_star
(paren
(paren
r_int
r_int
op_star
)paren
l_int|0xa0200020
)paren
suffix:semicolon
id|cobalt_is_raq
op_assign
(paren
id|cobalt_serial_present
op_ne
l_int|0x0
op_logical_and
id|cobalt_serial_type
op_eq
l_int|0x1
)paren
suffix:semicolon
)brace
r_void
id|AddTagsEndSymbol
c_func
(paren
r_void
)paren
suffix:semicolon
r_int
id|bi_TagAdd
(paren
r_enum
id|bi_tag
id|type
comma
r_int
r_int
id|size
comma
r_void
op_star
id|data
)paren
suffix:semicolon
DECL|variable|next_tag
r_int
r_int
id|next_tag
op_assign
(paren
r_int
r_int
)paren
l_int|NULL
suffix:semicolon
DECL|variable|memory_upper
r_int
r_int
id|memory_upper
op_assign
(paren
r_int
r_int
)paren
l_int|NULL
suffix:semicolon
DECL|function|bi_TagAdd
r_int
id|bi_TagAdd
(paren
r_enum
id|bi_tag
id|type
comma
r_int
r_int
id|size
comma
r_void
op_star
id|data
)paren
(brace
id|tag
id|t
suffix:semicolon
r_int
r_int
id|addr
suffix:semicolon
id|t.tag
op_assign
id|type
suffix:semicolon
id|t.size
op_assign
id|size
suffix:semicolon
multiline_comment|/*&n;&t; * If next_tag equals NULL it means it&squot;s the first tag we&squot;re asked&n;&t; * to create.&n;&t; */
r_if
c_cond
(paren
id|next_tag
op_eq
(paren
r_int
r_int
)paren
l_int|NULL
)paren
(brace
multiline_comment|/*&n;&t;&t; * If memory_upper not equals NULL it means that identify()&n;&t;&t; * was able to figure out how much memory is present in the&n;&t;&t; * box so we initialize next_tag from it.&n;&t;&t; */
r_if
c_cond
(paren
id|memory_upper
op_ne
(paren
r_int
r_int
)paren
l_int|NULL
)paren
id|next_tag
op_assign
id|memory_upper
suffix:semicolon
multiline_comment|/* Else we rely on the fact that the first tag we create for&n;&t;&t; * a box for which we don&squot;t know how RAM it gots is a tag of&n;&t;&t; * type tag_memupper.  This is ensured by the first entry in&n;&t;&t; * the defaults tag list for such a box (see identify.c).&n;&t;&t; * First we check this.&n;&t;&t; */
r_else
(brace
multiline_comment|/* Ok it&squot;s a memupper tag: we put it&squot;s value in &n;&t;&t;&t; * memory_upper so launch() can pass it to the&n;&t;&t;&t; * kernel in register a0 and we initialize next_tag.&n;&t;&t;&t; */
id|next_tag
op_assign
op_star
(paren
r_int
r_int
op_star
)paren
id|data
suffix:semicolon
id|memory_upper
op_assign
op_star
(paren
(paren
r_int
r_int
op_star
)paren
id|data
)paren
suffix:semicolon
)brace
)brace
multiline_comment|/* We put the tag structure.  */
id|addr
op_assign
id|next_tag
op_minus
(paren
r_sizeof
(paren
id|tag
)paren
)paren
suffix:semicolon
id|memcpy
(paren
(paren
r_void
op_star
)paren
id|addr
comma
(paren
r_void
op_star
)paren
op_amp
id|t
comma
(paren
r_int
)paren
(paren
r_sizeof
(paren
id|tag
)paren
)paren
)paren
suffix:semicolon
multiline_comment|/* We put the tag&squot;s data if any.  */
r_if
c_cond
(paren
id|size
op_ne
l_int|0
)paren
(brace
id|addr
op_assign
id|addr
op_minus
id|size
suffix:semicolon
id|memcpy
(paren
(paren
r_void
op_star
)paren
id|addr
comma
id|data
comma
(paren
r_int
)paren
(paren
id|t.size
)paren
)paren
suffix:semicolon
)brace
multiline_comment|/*&n;&t; * Set next_tag ready for the next tag creation.&n;&t; */
id|next_tag
op_assign
id|addr
suffix:semicolon
id|AddTagsEndSymbol
c_func
(paren
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
DECL|function|SetUpBootInfo
r_void
id|SetUpBootInfo
c_func
(paren
r_void
)paren
(brace
r_int
r_int
id|LongVar
suffix:semicolon
r_int
id|atag
suffix:semicolon
multiline_comment|/*&n;&t; * This is hard coded here but will change when we have a&n;&t; * Size mem routine.&n;&t; */
multiline_comment|/*&n;&t; * 64mb of memory.&n;&t; */
singleline_comment|//mips_memory_upper = 0x84000000;
macro_line|#ifndef BOOTLOADER
macro_line|#if 0&t;/* You break&squot;a the kernel I break&squot;a ya face. -DaveM */
multiline_comment|/* Eight meg of memory.         */
id|mips_memory_upper
op_assign
l_int|0x80800000
suffix:semicolon
multiline_comment|/* XXX  this appears to be unused  - &n;                                           this assignment is not present in the normal&n;                                           $cvstree/linux/arch/mips/cobalt/setup.c */
macro_line|#endif
macro_line|#else
macro_line|#include &quot;../../../../include/diagdefs.h&quot;
id|mips_memory_upper
op_assign
(paren
r_int
r_int
)paren
id|kBootloaderMipsMemoryUpper
suffix:semicolon
macro_line|#endif
id|LongVar
op_assign
id|mips_memory_upper
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_memupper
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
multiline_comment|/* Here is the machine type.&n;&t;*/
id|LongVar
op_assign
id|MACH_COBALT_27
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_machtype
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
l_int|0x80000000
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_memlower
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
id|CPU_R4300
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_cputype
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
id|MACH_GROUP_COBALT
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_machgroup
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
l_int|0
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_scache_size
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
l_int|48
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_tlb_entries
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
l_int|0
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_drive_info
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
l_int|0xe0800000
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_vram_base
comma
id|ULONGSIZE
comma
op_amp
id|LongVar
)paren
suffix:semicolon
id|LongVar
op_assign
l_int|0
suffix:semicolon
id|atag
op_assign
id|bi_TagAdd
c_func
(paren
id|tag_dummy
comma
l_int|0
comma
op_amp
id|LongVar
)paren
suffix:semicolon
)brace
DECL|function|AddTagsEndSymbol
r_void
id|AddTagsEndSymbol
c_func
(paren
r_void
)paren
(brace
r_int
id|X
suffix:semicolon
id|X
op_assign
l_int|1
suffix:semicolon
)brace
multiline_comment|/*&n; * Oh shit, this is so crappy ...&n; */
macro_line|#include &lt;linux/mm.h&gt;
macro_line|#include &lt;asm/pgtable.h&gt;
DECL|function|my_cacheflush
r_int
id|my_cacheflush
c_func
(paren
r_int
r_int
id|start
comma
r_int
r_int
id|size
comma
r_int
r_int
id|what
)paren
(brace
id|flush_cache_range
c_func
(paren
id|current-&gt;mm
comma
id|start
comma
id|start
op_plus
id|size
)paren
suffix:semicolon
r_return
l_int|0
suffix:semicolon
)brace
multiline_comment|/*&n; * The ROM set the flag to 0x1 to turn off output.  This is interpreted&n; * as &quot;valid&quot;, &quot;no kernel output&quot;, and index &squot;0&squot; into the following&n; * tables.  We overload entry &squot;0&squot; to specify a sensible default rate.&n; */
DECL|variable|cons_baud_int
r_static
r_int
id|cons_baud_int
(braket
)braket
op_assign
(brace
l_int|9600
comma
l_int|0
comma
l_int|9600
comma
l_int|0
comma
l_int|0
comma
l_int|115200
comma
l_int|0
comma
l_int|0
)brace
suffix:semicolon
DECL|variable|cons_baud_baud
r_static
r_int
id|cons_baud_baud
(braket
)braket
op_assign
(brace
id|B9600
comma
l_int|0
comma
id|B9600
comma
l_int|0
comma
l_int|0
comma
id|B115200
comma
l_int|0
comma
l_int|0
)brace
suffix:semicolon
r_static
r_union
id|cobalt_cons_info
DECL|function|cobalt_get_console_info
id|cobalt_get_console_info
c_func
(paren
r_void
)paren
(brace
r_char
id|board_id
op_assign
l_int|0
suffix:semicolon
r_static
r_union
id|cobalt_cons_info
id|cons_info
suffix:semicolon
r_static
r_int
id|read_info
op_assign
l_int|0
suffix:semicolon
r_extern
r_void
id|add_init_env
c_func
(paren
r_char
op_star
)paren
suffix:semicolon
r_if
c_cond
(paren
id|read_info
)paren
r_return
id|cons_info
suffix:semicolon
id|VIA_PORT_WRITE
c_func
(paren
id|VIA_CMOS_ADDR
comma
id|VIA_CMOS_CONSOLE_FLG
)paren
suffix:semicolon
id|cons_info.ccons_char
op_assign
id|VIA_PORT_READ
c_func
(paren
id|VIA_CMOS_DATA
)paren
suffix:semicolon
macro_line|#if 0
id|printk
c_func
(paren
l_string|&quot;cobalt_get_console_info: read 0x%x from console flag&bslash;n&quot;
comma
id|cons_info.ccons_char
)paren
suffix:semicolon
macro_line|#endif
multiline_comment|/*&n;&t; * CMOS hasn&squot;t been initialized or baud rate isn&squot;t known.&n;&t; * - read the board id and provide backwards compat.&n;&t; */
r_if
c_cond
(paren
id|cons_info.ccons_bits.valid
op_ne
id|VIA_CMOS_CONS_VALID
op_logical_or
op_logical_neg
id|cons_baud_int
(braket
id|cons_info.ccons_bits.baud
)braket
op_logical_or
op_logical_neg
id|cons_baud_baud
(braket
id|cons_info.ccons_bits.baud
)braket
)paren
(brace
id|pcibios_read_config_byte
c_func
(paren
l_int|0
comma
id|PCI_DEVSHFT
c_func
(paren
id|COBALT_PCICONF_VIA
)paren
comma
id|VIA_COBALT_BRD_ID_REG
comma
op_amp
id|board_id
)paren
suffix:semicolon
macro_line|#if 0
id|printk
c_func
(paren
l_string|&quot;cobalt_get_console_info: read 0x%x from board config&bslash;n&quot;
comma
id|board_id
)paren
suffix:semicolon
macro_line|#endif
r_switch
c_cond
(paren
id|VIA_COBALT_BRD_REG_to_ID
c_func
(paren
id|board_id
)paren
)paren
(brace
r_case
id|COBALT_BRD_ID_QUBE1
suffix:colon
id|cons_info.ccons_bits.baud
op_assign
id|VIA_CMOS_CONS_115K
suffix:semicolon
id|cons_info.ccons_bits.kout
op_assign
l_int|1
suffix:semicolon
r_break
suffix:semicolon
r_case
id|COBALT_BRD_ID_RAQ1
suffix:colon
id|cons_info.ccons_bits.baud
op_assign
id|VIA_CMOS_CONS_9600
suffix:semicolon
id|cons_info.ccons_bits.kout
op_assign
l_int|1
suffix:semicolon
r_break
suffix:semicolon
r_case
id|COBALT_BRD_ID_QUBE2
suffix:colon
id|cons_info.ccons_bits.baud
op_assign
id|VIA_CMOS_CONS_9600
suffix:semicolon
id|cons_info.ccons_bits.kout
op_assign
l_int|0
suffix:semicolon
r_break
suffix:semicolon
r_case
id|COBALT_BRD_ID_RAQ2
suffix:colon
id|cons_info.ccons_bits.baud
op_assign
id|VIA_CMOS_CONS_9600
suffix:semicolon
id|cons_info.ccons_bits.kout
op_assign
l_int|1
suffix:semicolon
r_break
suffix:semicolon
)brace
id|cons_info.ccons_bits.valid
op_assign
id|VIA_CMOS_CONS_VALID
suffix:semicolon
)brace
id|read_info
op_assign
l_int|1
suffix:semicolon
macro_line|#if defined(DEBUG_LOADER)
id|cons_info.ccons_bits.kout
op_assign
l_int|1
suffix:semicolon
macro_line|#endif
r_if
c_cond
(paren
op_logical_neg
id|cons_info.ccons_bits.kout
)paren
(brace
id|add_init_env
c_func
(paren
l_string|&quot;CONSOLE=/dev/null&quot;
)paren
suffix:semicolon
)brace
macro_line|#if 0
id|printk
c_func
(paren
l_string|&quot;cobalt_get_console_info: returning 0x%x&bslash;n&quot;
comma
id|cons_info.ccons_char
)paren
suffix:semicolon
macro_line|#endif
r_return
id|cons_info
suffix:semicolon
)brace
r_int
DECL|function|cobalt_cons_koutok
id|cobalt_cons_koutok
c_func
(paren
r_void
)paren
(brace
r_union
id|cobalt_cons_info
id|cons
suffix:semicolon
id|cons
op_assign
id|cobalt_get_console_info
c_func
(paren
)paren
suffix:semicolon
r_return
id|cons.ccons_bits.kout
suffix:semicolon
)brace
r_int
DECL|function|cobalt_cons_baudbaud
id|cobalt_cons_baudbaud
c_func
(paren
r_void
)paren
(brace
r_union
id|cobalt_cons_info
id|cons
suffix:semicolon
id|cons
op_assign
id|cobalt_get_console_info
c_func
(paren
)paren
suffix:semicolon
r_return
id|cons_baud_baud
(braket
id|cons.ccons_bits.baud
)braket
suffix:semicolon
)brace
r_int
DECL|function|cobalt_cons_baudint
id|cobalt_cons_baudint
c_func
(paren
r_void
)paren
(brace
r_union
id|cobalt_cons_info
id|cons
suffix:semicolon
id|cons
op_assign
id|cobalt_get_console_info
c_func
(paren
)paren
suffix:semicolon
r_return
id|cons_baud_int
(braket
id|cons.ccons_bits.baud
)braket
suffix:semicolon
)brace
eof
