multiline_comment|/* DO NOT TOUCH, AUTOGENERATED BY OFFSET.C */
macro_line|#ifndef _MIPS_OFFSET_H
DECL|macro|_MIPS_OFFSET_H
mdefine_line|#define _MIPS_OFFSET_H
multiline_comment|/* MIPS pt_regs offsets. */
DECL|macro|PT_R0
mdefine_line|#define PT_R0     24
DECL|macro|PT_R1
mdefine_line|#define PT_R1     28
DECL|macro|PT_R2
mdefine_line|#define PT_R2     32
DECL|macro|PT_R3
mdefine_line|#define PT_R3     36
DECL|macro|PT_R4
mdefine_line|#define PT_R4     40
DECL|macro|PT_R5
mdefine_line|#define PT_R5     44
DECL|macro|PT_R6
mdefine_line|#define PT_R6     48
DECL|macro|PT_R7
mdefine_line|#define PT_R7     52
DECL|macro|PT_R8
mdefine_line|#define PT_R8     56
DECL|macro|PT_R9
mdefine_line|#define PT_R9     60
DECL|macro|PT_R10
mdefine_line|#define PT_R10    64
DECL|macro|PT_R11
mdefine_line|#define PT_R11    68
DECL|macro|PT_R12
mdefine_line|#define PT_R12    72
DECL|macro|PT_R13
mdefine_line|#define PT_R13    76
DECL|macro|PT_R14
mdefine_line|#define PT_R14    80
DECL|macro|PT_R15
mdefine_line|#define PT_R15    84
DECL|macro|PT_R16
mdefine_line|#define PT_R16    88
DECL|macro|PT_R17
mdefine_line|#define PT_R17    92
DECL|macro|PT_R18
mdefine_line|#define PT_R18    96
DECL|macro|PT_R19
mdefine_line|#define PT_R19    100
DECL|macro|PT_R20
mdefine_line|#define PT_R20    104
DECL|macro|PT_R21
mdefine_line|#define PT_R21    108
DECL|macro|PT_R22
mdefine_line|#define PT_R22    112
DECL|macro|PT_R23
mdefine_line|#define PT_R23    116
DECL|macro|PT_R24
mdefine_line|#define PT_R24    120
DECL|macro|PT_R25
mdefine_line|#define PT_R25    124
DECL|macro|PT_R26
mdefine_line|#define PT_R26    128
DECL|macro|PT_R27
mdefine_line|#define PT_R27    132
DECL|macro|PT_R28
mdefine_line|#define PT_R28    136
DECL|macro|PT_R29
mdefine_line|#define PT_R29    140
DECL|macro|PT_R30
mdefine_line|#define PT_R30    144
DECL|macro|PT_R31
mdefine_line|#define PT_R31    148
DECL|macro|PT_LO
mdefine_line|#define PT_LO     152
DECL|macro|PT_HI
mdefine_line|#define PT_HI     156
DECL|macro|PT_OR2
mdefine_line|#define PT_OR2    160
DECL|macro|PT_OR7
mdefine_line|#define PT_OR7    164
DECL|macro|PT_EPC
mdefine_line|#define PT_EPC    168
DECL|macro|PT_BVADDR
mdefine_line|#define PT_BVADDR 172
DECL|macro|PT_STATUS
mdefine_line|#define PT_STATUS 176
DECL|macro|PT_CAUSE
mdefine_line|#define PT_CAUSE  180
DECL|macro|PT_SIZE
mdefine_line|#define PT_SIZE   184
multiline_comment|/* MIPS task_struct offsets. */
DECL|macro|TASK_STATE
mdefine_line|#define TASK_STATE         0
DECL|macro|TASK_COUNTER
mdefine_line|#define TASK_COUNTER       4
DECL|macro|TASK_PRIORITY
mdefine_line|#define TASK_PRIORITY      8
DECL|macro|TASK_SIGNAL
mdefine_line|#define TASK_SIGNAL        12
DECL|macro|TASK_BLOCKED
mdefine_line|#define TASK_BLOCKED       16
DECL|macro|TASK_FLAGS
mdefine_line|#define TASK_FLAGS         20
DECL|macro|TASK_MM
mdefine_line|#define TASK_MM            912
multiline_comment|/* MIPS specific thread_struct offsets. */
DECL|macro|THREAD_REG16
mdefine_line|#define THREAD_REG16   544
DECL|macro|THREAD_REG17
mdefine_line|#define THREAD_REG17   548
DECL|macro|THREAD_REG18
mdefine_line|#define THREAD_REG18   552
DECL|macro|THREAD_REG19
mdefine_line|#define THREAD_REG19   556
DECL|macro|THREAD_REG20
mdefine_line|#define THREAD_REG20   560
DECL|macro|THREAD_REG21
mdefine_line|#define THREAD_REG21   564
DECL|macro|THREAD_REG22
mdefine_line|#define THREAD_REG22   568
DECL|macro|THREAD_REG23
mdefine_line|#define THREAD_REG23   572
DECL|macro|THREAD_REG28
mdefine_line|#define THREAD_REG28   576
DECL|macro|THREAD_REG29
mdefine_line|#define THREAD_REG29   580
DECL|macro|THREAD_REG30
mdefine_line|#define THREAD_REG30   584
DECL|macro|THREAD_REG31
mdefine_line|#define THREAD_REG31   588
DECL|macro|THREAD_STATUS
mdefine_line|#define THREAD_STATUS  592
DECL|macro|THREAD_FPU
mdefine_line|#define THREAD_FPU     600
DECL|macro|THREAD_BVADDR
mdefine_line|#define THREAD_BVADDR  864
DECL|macro|THREAD_ECODE
mdefine_line|#define THREAD_ECODE   868
DECL|macro|THREAD_TRAPNO
mdefine_line|#define THREAD_TRAPNO  872
DECL|macro|THREAD_KSP
mdefine_line|#define THREAD_KSP     876
DECL|macro|THREAD_PGDIR
mdefine_line|#define THREAD_PGDIR   880
DECL|macro|THREAD_MFLAGS
mdefine_line|#define THREAD_MFLAGS  884
DECL|macro|THREAD_CURDS
mdefine_line|#define THREAD_CURDS   888
DECL|macro|THREAD_TRAMP
mdefine_line|#define THREAD_TRAMP   892
DECL|macro|THREAD_OLDCTX
mdefine_line|#define THREAD_OLDCTX  896
multiline_comment|/* Linux mm_struct offsets. */
DECL|macro|MM_COUNT
mdefine_line|#define MM_COUNT      12
DECL|macro|MM_PGD
mdefine_line|#define MM_PGD        8
DECL|macro|MM_CONTEXT
mdefine_line|#define MM_CONTEXT    28
macro_line|#endif /* !(_MIPS_OFFSET_H) */
eof
