multiline_comment|/*&n; * WARNING! This file is automatically generated - DO NOT EDIT!&n; */
DECL|macro|TS_MAGICKEY
mdefine_line|#define TS_MAGICKEY&t;0x5a5a5a5a
DECL|macro|TS_TSS
mdefine_line|#define TS_TSS 478
DECL|macro|TS_ESP0
mdefine_line|#define TS_ESP0 498
DECL|macro|TS_FPU
mdefine_line|#define TS_FPU 502
eof
