multiline_comment|/*&n; * WARNING! This file is automatically generated - DO NOT EDIT!&n; */
DECL|macro|TS_MAGICKEY
mdefine_line|#define TS_MAGICKEY&t;0x5a5a5a5a
DECL|macro|TASK_STATE
mdefine_line|#define TASK_STATE 0
DECL|macro|TASK_FLAGS
mdefine_line|#define TASK_FLAGS 4
DECL|macro|TASK_SIGPENDING
mdefine_line|#define TASK_SIGPENDING 8
DECL|macro|TASK_NEEDRESCHED
mdefine_line|#define TASK_NEEDRESCHED 20
DECL|macro|TASK_THREAD
mdefine_line|#define TASK_THREAD 482
DECL|macro|TASK_MM
mdefine_line|#define TASK_MM 634
DECL|macro|TASK_ACTIVE_MM
mdefine_line|#define TASK_ACTIVE_MM 638
DECL|macro|THREAD_KSP
mdefine_line|#define THREAD_KSP 0
DECL|macro|THREAD_USP
mdefine_line|#define THREAD_USP 4
DECL|macro|THREAD_SR
mdefine_line|#define THREAD_SR 8
DECL|macro|THREAD_FS
mdefine_line|#define THREAD_FS 10
DECL|macro|THREAD_CRP
mdefine_line|#define THREAD_CRP 12
DECL|macro|THREAD_ESP0
mdefine_line|#define THREAD_ESP0 20
DECL|macro|THREAD_FPREG
mdefine_line|#define THREAD_FPREG 24
DECL|macro|THREAD_FPCNTL
mdefine_line|#define THREAD_FPCNTL 120
DECL|macro|THREAD_FPSTATE
mdefine_line|#define THREAD_FPSTATE 132
DECL|macro|PT_D0
mdefine_line|#define PT_D0 32
DECL|macro|PT_ORIG_D0
mdefine_line|#define PT_ORIG_D0 36
DECL|macro|PT_D1
mdefine_line|#define PT_D1 0
DECL|macro|PT_D2
mdefine_line|#define PT_D2 4
DECL|macro|PT_D3
mdefine_line|#define PT_D3 8
DECL|macro|PT_D4
mdefine_line|#define PT_D4 12
DECL|macro|PT_D5
mdefine_line|#define PT_D5 16
DECL|macro|PT_A0
mdefine_line|#define PT_A0 20
DECL|macro|PT_A1
mdefine_line|#define PT_A1 24
DECL|macro|PT_A2
mdefine_line|#define PT_A2 28
DECL|macro|PT_PC
mdefine_line|#define PT_PC 46
DECL|macro|PT_SR
mdefine_line|#define PT_SR 44
DECL|macro|PT_VECTOR
mdefine_line|#define PT_VECTOR 50
DECL|macro|IRQ_HANDLER
mdefine_line|#define IRQ_HANDLER 0
DECL|macro|IRQ_DEVID
mdefine_line|#define IRQ_DEVID 8
DECL|macro|IRQ_NEXT
mdefine_line|#define IRQ_NEXT 16
DECL|macro|STAT_IRQ
mdefine_line|#define STAT_IRQ 120
DECL|macro|BIR_TAG
mdefine_line|#define BIR_TAG 0
DECL|macro|BIR_SIZE
mdefine_line|#define BIR_SIZE 2
DECL|macro|BIR_DATA
mdefine_line|#define BIR_DATA 4
DECL|macro|FBCON_FONT_DESC_IDX
mdefine_line|#define FBCON_FONT_DESC_IDX 0
DECL|macro|FBCON_FONT_DESC_NAME
mdefine_line|#define FBCON_FONT_DESC_NAME 4
DECL|macro|FBCON_FONT_DESC_WIDTH
mdefine_line|#define FBCON_FONT_DESC_WIDTH 8
DECL|macro|FBCON_FONT_DESC_HEIGHT
mdefine_line|#define FBCON_FONT_DESC_HEIGHT 12
DECL|macro|FBCON_FONT_DESC_DATA
mdefine_line|#define FBCON_FONT_DESC_DATA 16
DECL|macro|FBCON_FONT_DESC_PREF
mdefine_line|#define FBCON_FONT_DESC_PREF 20
DECL|macro|SIGSEGV
mdefine_line|#define SIGSEGV 11
DECL|macro|SEGV_MAPERR
mdefine_line|#define SEGV_MAPERR 1
DECL|macro|SIGTRAP
mdefine_line|#define SIGTRAP 5
DECL|macro|TRAP_TRACE
mdefine_line|#define TRAP_TRACE 2
DECL|macro|CUSTOMBASE
mdefine_line|#define CUSTOMBASE -2132807680
DECL|macro|C_INTENAR
mdefine_line|#define C_INTENAR 28
DECL|macro|C_INTREQR
mdefine_line|#define C_INTREQR 30
DECL|macro|C_INTENA
mdefine_line|#define C_INTENA 154
DECL|macro|C_INTREQ
mdefine_line|#define C_INTREQ 156
DECL|macro|C_SERDATR
mdefine_line|#define C_SERDATR 24
DECL|macro|C_SERDAT
mdefine_line|#define C_SERDAT 48
DECL|macro|C_SERPER
mdefine_line|#define C_SERPER 50
DECL|macro|CIAABASE
mdefine_line|#define CIAABASE -2134908927
DECL|macro|CIABBASE
mdefine_line|#define CIABBASE -2134913024
DECL|macro|C_PRA
mdefine_line|#define C_PRA 0
DECL|macro|ZTWOBASE
mdefine_line|#define ZTWOBASE -2147483648
eof
