multiline_comment|/*&n; * WARNING! This file is automatically generated - DO NOT EDIT!&n; */
DECL|macro|TS_MAGICKEY
mdefine_line|#define TS_MAGICKEY&t;0x5a5a5a5a
DECL|macro|TASK_STATE
mdefine_line|#define TASK_STATE 0
DECL|macro|TASK_FLAGS
mdefine_line|#define TASK_FLAGS 4
DECL|macro|TASK_SIGPENDING
mdefine_line|#define TASK_SIGPENDING 8
DECL|macro|TASK_NEEDRESCHED
mdefine_line|#define TASK_NEEDRESCHED 20
DECL|macro|TASK_TSS
mdefine_line|#define TASK_TSS 470
DECL|macro|TASK_MM
mdefine_line|#define TASK_MM 622
DECL|macro|TSS_KSP
mdefine_line|#define TSS_KSP 0
DECL|macro|TSS_USP
mdefine_line|#define TSS_USP 4
DECL|macro|TSS_SR
mdefine_line|#define TSS_SR 8
DECL|macro|TSS_FS
mdefine_line|#define TSS_FS 10
DECL|macro|TSS_CRP
mdefine_line|#define TSS_CRP 12
DECL|macro|TSS_ESP0
mdefine_line|#define TSS_ESP0 20
DECL|macro|TSS_FPREG
mdefine_line|#define TSS_FPREG 24
DECL|macro|TSS_FPCNTL
mdefine_line|#define TSS_FPCNTL 120
DECL|macro|TSS_FPSTATE
mdefine_line|#define TSS_FPSTATE 132
DECL|macro|PT_D0
mdefine_line|#define PT_D0 32
DECL|macro|PT_ORIG_D0
mdefine_line|#define PT_ORIG_D0 36
DECL|macro|PT_SR
mdefine_line|#define PT_SR 44
DECL|macro|PT_VECTOR
mdefine_line|#define PT_VECTOR 50
DECL|macro|IRQ_HANDLER
mdefine_line|#define IRQ_HANDLER 0
DECL|macro|IRQ_DEVID
mdefine_line|#define IRQ_DEVID 8
DECL|macro|IRQ_NEXT
mdefine_line|#define IRQ_NEXT 16
DECL|macro|STAT_IRQ
mdefine_line|#define STAT_IRQ 120
DECL|macro|BIR_TAG
mdefine_line|#define BIR_TAG 0
DECL|macro|BIR_SIZE
mdefine_line|#define BIR_SIZE 2
DECL|macro|BIR_DATA
mdefine_line|#define BIR_DATA 4
DECL|macro|FBCON_FONT_DESC_IDX
mdefine_line|#define FBCON_FONT_DESC_IDX 0
DECL|macro|FBCON_FONT_DESC_NAME
mdefine_line|#define FBCON_FONT_DESC_NAME 4
DECL|macro|FBCON_FONT_DESC_WIDTH
mdefine_line|#define FBCON_FONT_DESC_WIDTH 8
DECL|macro|FBCON_FONT_DESC_HEIGHT
mdefine_line|#define FBCON_FONT_DESC_HEIGHT 12
DECL|macro|FBCON_FONT_DESC_DATA
mdefine_line|#define FBCON_FONT_DESC_DATA 16
DECL|macro|FBCON_FONT_DESC_PREF
mdefine_line|#define FBCON_FONT_DESC_PREF 20
DECL|macro|CUSTOMBASE
mdefine_line|#define CUSTOMBASE -2132807680
DECL|macro|C_INTENAR
mdefine_line|#define C_INTENAR 28
DECL|macro|C_INTREQR
mdefine_line|#define C_INTREQR 30
DECL|macro|C_INTENA
mdefine_line|#define C_INTENA 154
DECL|macro|C_INTREQ
mdefine_line|#define C_INTREQ 156
DECL|macro|C_SERDATR
mdefine_line|#define C_SERDATR 24
DECL|macro|C_SERDAT
mdefine_line|#define C_SERDAT 48
DECL|macro|C_SERPER
mdefine_line|#define C_SERPER 50
DECL|macro|CIAABASE
mdefine_line|#define CIAABASE -2134908927
DECL|macro|CIABBASE
mdefine_line|#define CIABBASE -2134913024
DECL|macro|C_PRA
mdefine_line|#define C_PRA 0
DECL|macro|ZTWOBASE
mdefine_line|#define ZTWOBASE -2147483648
eof
